// effect audio group definitions
function create_effect_group(name, count) {
  var obj = {
    'name': name,
    'audio': [],
  };
  for (let i = 1; i <= count; i += 1) {
    obj.audio.push('./effects/' + name + ' ' + i.toString() + '.ogg');
  }
  return obj;
}
var effect_groups = {
  'arrow loose and hit': 7,
  'dirt slam': 4,
  'dragon bite': 2,
  'ooze': 5,
  'owlbear roar': 4,
  'slam attack': 4,
  'swimming': 6,
  'sword clash': 3,
  'thunder clap': 4,
  'wave crash': 4,
};
for (let name in effect_groups) {
  let count = effect_groups[name]
  effect_groups[name] = create_effect_group(name, count);
}


// Specific soundboards
var soundboards = {}
soundboards.Car = [
  './MP3/Car/car 1 door open.mp3',
  './MP3/Car/car 2 door close.mp3',
  './MP3/Car/car 3 handbrake release.mp3',
  './MP3/Car/car 4 seat belt.mp3',
  './MP3/Car/car 5 key ignition insert.mp3',
  './MP3/Car/car 6 ignition.mp3',
  './MP3/Car/car 7 idle engine sound late evening 1 hour.mp3',
  './MP3/Car/car 8 driving 45 minetes.mp3',
  './MP3/Car/car turn signal.mp3',
  './MP3/Car/car window open.mp3',
  './MP3/Car/car seatbelt alarm.mp3',
  './MP3/Car/car horn sound effect 1.mp3',
  './MP3/Car/car horn sound effect 2.mp3',
  './MP3/Car/car horn traffic sound effect.mp3',
  './MP3/Car/car ambulance siren approach and drive by.mp3',
  './MP3/Car/car fire truck siren pass by.mp3',
  './MP3/Car/car police sirens passing by.mp3',
  './MP3/Car/car driving in the rain.mp3',
  './MP3/Car/8 hours of car driving sound effect   car sound effect   car driving sound and car noises.mp3',
  './MP3/Car/car passing.mp3',
  './MP3/Car/car radio los santos rock radio.mp3',
  './MP3/Car/car radio non stop pop radio.mp3',
  './MP3/Car/car radio rebel radio grand theft auto 5.mp3',
  './MP3/Car/car radio vinewood boulevard radio grand theft auto 5.mp3',
  './MP3/Car/car radio 10 grand thef tauto sanandreas.mp3',
];

soundboards.Store_Clerk = [
  './MP3/Store_Clerk/How muchts do you need.mp3',
  './MP3/Store_Clerk/we have a new policy about large transactions and will no longer be able to complete this order due to the suspicious nature i do truly apologize for the inconvenience.mp3',
  './MP3/Store_Clerk/i apologize for the inconvenience.mp3',
  './MP3/Store_Clerk/its for a party its for a family member that wont be anny issue.mp3',
  './MP3/Store_Clerk/oooo i see.mp3',
  './MP3/Store_Clerk/ok.mp3',
  './MP3/Store_Clerk/o that is allot.mp3',
  './MP3/Store_Clerk/bye now.mp3',
  './MP3/Store_Clerk/come back and see you soon.mp3',
  './MP3/Store_Clerk/hello Sir.mp3',
  './MP3/Store_Clerk/origth you have a  realy good day thank you.mp3',
  './MP3/Store_Clerk/that is fine can i m have you with somthing els.mp3',
];

soundboards.Child = [
  './MP3/child/ahh.ogg',
  './MP3/child/are we there yet.ogg',
  './MP3/child/can you help me with myn home work.ogg',
  './MP3/child/can i m have a snack.ogg',
  './MP3/child/can i m have some ice cream.ogg',
  './MP3/child/com doesend work.ogg',
  './MP3/child/computer is locked.ogg',
  './MP3/child/dad.ogg',
  './MP3/child/daddie.ogg',
  './MP3/child/daddy 1.ogg',
  './MP3/child/daddy 2.ogg',
  './MP3/child/Dont play game with me.ogg',
  './MP3/child/Giggle.ogg',
  './MP3/child/hello are you there.ogg',
  './MP3/child/hello i m talking.ogg',
  './MP3/child/i dont lie.ogg',
  './MP3/child/i m can read verry well.ogg',
  './MP3/child/i m click on it.ogg',
  './MP3/child/i m got a popup on myn computer.ogg',
  './MP3/child/i m have somthing the do.ogg',
  './MP3/child/i m life in the sewer  pipline.ogg',
  './MP3/child/i m live in the middle of nowhere.ogg',
  './MP3/child/i m never lie.ogg',
  './MP3/child/i m not a victum.ogg',
  './MP3/child/i m thirsty.ogg',
  './MP3/child/its install.ogg',
  './MP3/child/its not working.ogg',
  './MP3/child/listen to me.ogg',
  './MP3/child/lister to me.ogg',
  './MP3/child/look out.ogg',
  './MP3/child/mam 1.ogg',
  './MP3/child/mam 2.ogg',
  './MP3/child/mammie 1.ogg',
  './MP3/child/mammie 2.ogg',
  './MP3/child/my brother is theasing me.ogg',
  './MP3/child/my last name is oplichter.ogg',
  './MP3/child/myn brother broke myn toy.ogg',
  './MP3/child/myn fathert name is ben oplichter.ogg',
  './MP3/child/myn mom tells dont talk with strangers.ogg',
  './MP3/child/myn name is  sharon the miler.ogg',
  './MP3/child/myn name is laura.ogg',
  './MP3/child/no.ogg',
  './MP3/child/och everything is ok.ogg',
  './MP3/child/ok.ogg',
  './MP3/child/okee.ogg',
  './MP3/child/the wheel of the car is broken.ogg',
  './MP3/child/uhum.ogg',
  './MP3/child/what do i m need the do.ogg',
  './MP3/child/what is myn ip adderes.ogg',
  './MP3/child/all heil wob legend.ogg',
  './MP3/child/all heil the feret king.ogg',
  './MP3/child/who are you talking.ogg',
  './MP3/child/who are you.ogg',
  './MP3/child/who is on the phone.ogg',
  './MP3/child/yes i do.ogg',
  './MP3/child/yes.ogg',
];

soundboards.Wob_Legend = [
  './MP3/Wob/ad 1 june and come back on 14 june.mp3',
  './MP3/Wob/ad 10 april and come back on 17 april.mp3',
  './MP3/Wob/ad 12 december and come back on 26 december.mp3',
  './MP3/Wob/ad 15 july and come back on 22 july.mp3',
  './MP3/Wob/ad 15 march and come back on 30 march.mp3',
  './MP3/Wob/ad 2 oktober and come back on 16 oktober.mp3',
  './MP3/Wob/ad 20 february and come back on 27 february.mp3',
  './MP3/Wob/ad 22 august and come back on 29 august.mp3',
  './MP3/Wob/ad 3 may and come back on 17 may.mp3',
  './MP3/Wob/ad 5 january and come back on 19 january.mp3',
  './MP3/Wob/ad 5 november and come back on 12 november (1).mp3',
  './MP3/Wob/ad 5 november and come back on 12 november.mp3',
  './MP3/Wob/ad 7 september and come back on 21 september.mp3',
  './MP3/Wob/address 135 roosevelt ave queens new york zipcode11354.mp3',
  './MP3/Wob/address 2442 broadway new york zipcode10024.mp3',
  './MP3/Wob/address 66 main st flushing new york Zipcode 11367.mp3',
  './MP3/Wob/address 720 amsterdam ave new york ZipCode 10025.mp3',
  './MP3/Wob/address 955 columbus ave New York Zipcode 10025.mp3',
  './MP3/Wob/Credit Card 11 t 8 is 11 t 8.mp3',
  './MP3/Wob/Credit Card = are you playing 11 t 8  = 11 t 8.mp3',
  './MP3/Wob/Credit Card cvv 529.mp3',
  './MP3/Wob/Credit Card cvv 919.mp3',
  './MP3/Wob/Credit Card exp 10 2023 (1).mp3',
  './MP3/Wob/Credit Card exp 10 2023.mp3',
  './MP3/Wob/Credit Card exp 15 2022.mp3',
  './MP3/Wob/Credit Card exp 20 2025.mp3',
  './MP3/Wob/Credit Card exp 6 2024 (1).mp3',
  './MP3/Wob/Credit Card exp 6 2024.mp3',
  './MP3/Wob/Credit Card Mastercard 1 5330944963789523.mp3',
  './MP3/Wob/Credit Card Mastercard 1 9523 last digit.mp3',
  './MP3/Wob/Credit Card Mastercard 11 t 8 521539074360827 eleven t 8.mp3',
  './MP3/Wob/Credit Card Mastercard 11 t 8 536022237916671 eleven t 8.mp3',
  './MP3/Wob/Credit Card Mastercard 11 t 8 547545827499484 eleven t 8.mp3',
  './MP3/Wob/Credit Card Mastercard 11 t 8 549947689107703 eleven t 8.mp3',
  './MP3/Wob/Credit Card Mastercard 11 t 8 554223441382910 eleven t 8.mp3',
  './MP3/Wob/Credit Card mastercard.mp3',
  './MP3/Wob/Credit Card Visa 1 4345 last digit.mp3',
  './MP3/Wob/Credit Card Visa 1 4485146461394345.mp3',
  './MP3/Wob/Credit Card Visa 11 t 8 453947968971048.mp3',
  './MP3/Wob/Credit Card Visa 11 t 8 455690774137635.mp3',
  './MP3/Wob/Credit Card Visa 11 t 8 491668043682832.mp3',
  './MP3/Wob/Credit Card Visa 4532011759914142.mp3',
  './MP3/Wob/Credit Card Visa.mp3',
  './MP3/Wob/Curse =  2 tickel stick johnson error code 3dtfm4d its netsend packed.mp3',
  './MP3/Wob/Curse = 1 tickle stick johnson.mp3',
  './MP3/Wob/Curse = can you help me fix that problem from this ticket vendors under sunshine error code 3d tfm 4D to NetSendpacket.mp3',
  './MP3/Wob/Curse = can you help me install that come protection on my computer.mp3',
  './MP3/Wob/Curse = computer doesnt have cunt protection do you want the install it yes or no.mp3',
  './MP3/Wob/Curse = cunt is virus or firewall protection.mp3',
  './MP3/Wob/Curse = do not also remove the pickel from the poop shooter.mp3',
  './MP3/Wob/Curse = how big is your packed.mp3',
  './MP3/Wob/Curse = lister to me pickle dick licker i m got a issue you need to help me fixs it ok.mp3',
  './MP3/Wob/Curse = sonagachi jeebee road.mp3',
  './MP3/Wob/Curse = stick in here pussy.mp3',
  './MP3/Wob/Curse = stick it where the sun doesnt shine error code three dt 140 is not some packet but i dont know what that is.mp3',
  './MP3/Wob/Curse = still have the pickle in poop shooter.mp3',
  './MP3/Wob/Curse = take a glass off water and go fuck you self.mp3',
  './MP3/Wob/Curse = this computer have a paper stuck in the poop shoot or do you want to help me remove it yes or no.mp3',
  './MP3/Wob/even dont know what happened.mp3',
  './MP3/Wob/expleen me please.mp3',
  './MP3/Wob/Femal Cashcheer did you see our warning sign about scams this amount of money is suspicious i cant sell you them im sorry.mp3',
  './MP3/Wob/Give Card Voulcher = calling for 100 dollar voucher card.mp3',
  './MP3/Wob/Give Card Voulcher = i m calling for the gifcard voucher how do i m get it.mp3',
  './MP3/Wob/Give Card Voulcher = there is a warning sigth about scammes here what is that.mp3',
  './MP3/Wob/Give Card Voulcher = warning sighn payment gifcard.mp3',
  './MP3/Wob/Give Card Voulcher = what for gene gifcard do i m need to get.mp3',
  './MP3/Wob/Give Card Voulcher = yes hello i m calling for the gifcard voulcher.mp3',
  './MP3/Wob/hello hello are you there.mp3',
  './MP3/Wob/hello.mp3',
  './MP3/Wob/how long do this take.mp3',
  './MP3/Wob/how long will this take.mp3',
  './MP3/Wob/i m not a recording so what are you talk about.mp3',
  './MP3/Wob/i m the custumer and the custumer is always rigth so let me talk plz.mp3',
  './MP3/Wob/irs ssa hello sir i m calling allecation about myn name there is somthing wrong with myn social security or somthing.mp3',
  './MP3/Wob/lister to me are you there.mp3',
  './MP3/Wob/my name.mp3',
  './MP3/Wob/Name  =1 ben oplichter.mp3',
  './MP3/Wob/Name 1 jack hoffman.mp3',
  './MP3/Wob/Name 2 ben oplichter spelling (1).mp3',
  './MP3/Wob/Name 2 ben oplichter spelling.mp3',
  './MP3/Wob/Name 2 jack hoffman spelling.mp3',
  './MP3/Wob/no.mp3',
  './MP3/Wob/ok lister to me i m have a broblume and you need to help me fixs it.mp3',
  './MP3/Wob/ok no broblume.mp3',
  './MP3/Wob/ok sir.mp3',
  './MP3/Wob/ok well what is it.mp3',
  './MP3/Wob/ok what now.mp3',
  './MP3/Wob/ok.mp3',
  './MP3/Wob/SSA IRS im returning a phone call about legal allocation how do i fix that.mp3',
  './MP3/Wob/Tech Support = 3d tf m4 d.mp3',
  './MP3/Wob/Tech Support = broblum whit computer help me fixs it.mp3',
  './MP3/Wob/Tech Support = cannot click it away what do i need to do.mp3',
  './MP3/Wob/Tech Support = computer have mental issue fixs it plz.mp3',
  './MP3/Wob/Tech Support = criticel error on webpage.mp3',
  './MP3/Wob/Tech Support = do i m need to press run.mp3',
  './MP3/Wob/Tech Support = do you want to install it.mp3',
  './MP3/Wob/Tech Support = fake scammer popup info.mp3',
  './MP3/Wob/Tech Support = go to critical error on my computer.mp3',
  './MP3/Wob/Tech Support = i m click no what now.mp3',
  './MP3/Wob/Tech Support = im clicking yes but nothing happened.mp3',
  './MP3/Wob/Tech Support = im on the web page what now.mp3',
  './MP3/Wob/Tech Support = in dont know how.mp3',
  './MP3/Wob/Tech Support = in dont know what happened right now.mp3',
  './MP3/Wob/Tech Support = its installing wait moment.mp3',
  './MP3/Wob/Tech Support = that is the error code.mp3',
  './MP3/Wob/that is not good rigth.mp3',
  './MP3/Wob/uh huh.mp3',
  './MP3/Wob/what first lastname sir.mp3',
  './MP3/Wob/what happent.mp3',
  './MP3/Wob/what is your name (1).mp3',
  './MP3/Wob/what is your name.mp3',
  './MP3/Wob/what now.mp3',
  './MP3/Wob/whats your name.mp3',
  './MP3/Wob/yea hello are you there.mp3',
  './MP3/Wob/yeah.mp3',
  './MP3/Wob/yes or no.mp3',
  './MP3/Wob/yes sir.mp3',
];

soundboards.Stonewulf_Collection = [
  './MP3/Stonewulf/apple - angry rant hindi.mp3',
  './MP3/Stonewulf/apple - Ben chode.mp3',
  './MP3/Stonewulf/apple - cursing 1.mp3',
  './MP3/Stonewulf/apple - DO YOU GET THIS.mp3',
  './MP3/Stonewulf/apple - gandu.mp3',
  './MP3/Stonewulf/apple - greeting.mp3',
  './MP3/Stonewulf/apple - hindi cursing 1.mp3',
  './MP3/Stonewulf/apple - hindi cursing 2.mp3',
  './MP3/Stonewulf/apple - I beg your pardon.mp3',
  './MP3/Stonewulf/apple - LET ME DO MY JOB.mp3',
  './MP3/Stonewulf/apple - randia.mp3',
  './MP3/Stonewulf/apple - STUPID FOOL.mp3',
  './MP3/Stonewulf/apple - what kind of issue cpu.mp3',
  './MP3/Stonewulf/apple - you bastard.mp3',
  './MP3/Stonewulf/apple - you scoundrel.mp3',
  './MP3/Stonewulf/Baby Chappy.wav',
  './MP3/Stonewulf/BEN CHODE BLOODY.mp3',
  './MP3/Stonewulf/birthday sex-1.mp3',
  './MP3/Stonewulf/BLOODY BASTARD.mp3',
  './MP3/Stonewulf/BLOODY FUCK YOU.mp3',
  './MP3/Stonewulf/buzz off.mp3',
  './MP3/Stonewulf/call me back.mp3',
  './MP3/Stonewulf/cumshot.mp3',
  './MP3/Stonewulf/cursing 1.mp3',
  './MP3/Stonewulf/cursing 2.mp3',
  './MP3/Stonewulf/cursing 3.mp3',
  './MP3/Stonewulf/cursing 4.mp3',
  './MP3/Stonewulf/did you receive the call....mp3',
  './MP3/Stonewulf/Do you understand.mp3',
  './MP3/Stonewulf/egg sandwitch.mp3',
  './MP3/Stonewulf/first... I need to fuck your mom.mp3',
  './MP3/Stonewulf/greeting social security.mp3',
  './MP3/Stonewulf/greeting.mp3',
  './MP3/Stonewulf/haha f--- your mother.mp3',
  './MP3/Stonewulf/have you been to the state of baltimore.mp3',
  './MP3/Stonewulf/hello mother fucker (1).mp3',
  './MP3/Stonewulf/hello1.mp3',
  './MP3/Stonewulf/hindi 4.mp3',
  './MP3/Stonewulf/hindi 5.mp3',
  './MP3/Stonewulf/hold the line let me check it out.mp3',
  './MP3/Stonewulf/i gave your mother 10.mp3',
  './MP3/Stonewulf/i will fuck you.mp3',
  './MP3/Stonewulf/In order todo this first I need to fuck your mom okay1.mp3',
  './MP3/Stonewulf/INTERRUPT 1.mp3',
  './MP3/Stonewulf/INTERRUPT 2.mp3',
  './MP3/Stonewulf/INTERRUPT 3.mp3',
  './MP3/Stonewulf/INTERRUPT 4.mp3',
  './MP3/Stonewulf/Lady - Aha.mp3',
  './MP3/Stonewulf/Lady - Cursing 1.mp3',
  './MP3/Stonewulf/Lady - Cursing 2.mp3',
  './MP3/Stonewulf/Lady - Cursing 3.mp3',
  './MP3/Stonewulf/Lady - Cursing 4.mp3',
  './MP3/Stonewulf/Lady - Cursing 5.mp3',
  './MP3/Stonewulf/Lady - Cursing 6.mp3',
  './MP3/Stonewulf/Lady - Get a fucking life.mp3',
  './MP3/Stonewulf/Lady - Heh.mp3',
  './MP3/Stonewulf/Lady - Hohhh.mp3',
  './MP3/Stonewulf/Lady - Huh.mp3',
  './MP3/Stonewulf/MOTHER BLOODY.mp3',
  './MP3/Stonewulf/mother chode.mp3',
  './MP3/Stonewulf/please press 2 to fuck your girl fiend 1.mp3',
  './MP3/Stonewulf/recorded line.mp3',
  './MP3/Stonewulf/RUNNING LIKE LADY.mp3',
  './MP3/Stonewulf/scam line 1.mp3',
  './MP3/Stonewulf/scam line 2.mp3',
  './MP3/Stonewulf/scam line 3.mp3',
  './MP3/Stonewulf/scam line 4.mp3',
  './MP3/Stonewulf/scam line 5.mp3',
  './MP3/Stonewulf/shut up and fuck off.mp3',
  './MP3/Stonewulf/shut up.mp3',
  './MP3/Stonewulf/suck my dick 1.mp3',
  './MP3/Stonewulf/suck my dick 2.mp3',
  './MP3/Stonewulf/thank you for calling atnt.mp3',
  './MP3/Stonewulf/tu mother chode.mp3',
  './MP3/Stonewulf/we know that.mp3',
  './MP3/Stonewulf/WHY U SALTING AT ME.mp3',
  './MP3/Stonewulf/WHY YOU FUCK ME.mp3',
  './MP3/Stonewulf/write down my name.mp3',
  './MP3/Stonewulf/WTF MAN.mp3',
  './MP3/Stonewulf/yes sir.mp3',
  './MP3/Stonewulf/yes.mp3',
  './MP3/Stonewulf/you got a pen.mp3',
  './MP3/Stonewulf/You know I Fed your mother.mp3',
  './MP3/Stonewulf/you know i.. lol.mp3',
  './MP3/Stonewulf/you mother chode.mp3',
  './MP3/Stonewulf/you think u are smarter than me sob.mp3',
  './MP3/Stonewulf/you want to take that number in your ass.mp3',
  './MP3/Stonewulf/your accent is not like english.mp3',
  './MP3/Stonewulf/your mother told me she slept with 10 different guys.mp3',
];

soundboards.Pecanhead_Collection = [
  './MP3/Pecanhead/a1.mp3',
  './MP3/Pecanhead/a2.mp3',
  './MP3/Pecanhead/a3.mp3',
  './MP3/Pecanhead/a4.mp3',
  './MP3/Pecanhead/a5.mp3',
  './MP3/Pecanhead/a6.mp3',
  './MP3/Pecanhead/a7.mp3',
  './MP3/Pecanhead/aaa.mp3',
  './MP3/Pecanhead/AIRHORN.mp3',
  './MP3/Pecanhead/assless chaps.mp3',
  './MP3/Pecanhead/audio (1).wav',
  './MP3/Pecanhead/audio.wav',
  './MP3/Pecanhead/b1.mp3',
  './MP3/Pecanhead/b2.mp3',
  './MP3/Pecanhead/baby shark dance sing and dance animal songs pinkfong songs for children audiotrimmer.mp3',
  './MP3/Pecanhead/badumtss.swf.mp3',
  './MP3/Pecanhead/Bitch.mp3',
  './MP3/Pecanhead/bo.mp3',
  './MP3/Pecanhead/call me.mp3',
  './MP3/Pecanhead/can i rape you analy.mp3',
  './MP3/Pecanhead/cant believe it.mp3',
  './MP3/Pecanhead/Charlie Cream Pie.mp3',
  './MP3/Pecanhead/charlie master.mp3',
  './MP3/Pecanhead/clown horn sound effect_1.mp3',
  './MP3/Pecanhead/come in naked.mp3',
  './MP3/Pecanhead/couple guys from chicago.mp3',
  './MP3/Pecanhead/DEX DONT GIVE A FK.mp3',
  './MP3/Pecanhead/did an awful nasty awful things and they go written like would down like that they hoped.mp3',
  './MP3/Pecanhead/do u know the movie with a man.mp3',
  './MP3/Pecanhead/donald duck scammer.mp3',
  './MP3/Pecanhead/dont be sure.mp3',
  './MP3/Pecanhead/dont make me beg.mp3',
  './MP3/Pecanhead/dr fell bitch.mp3',
  './MP3/Pecanhead/DR FELL PANTIES.mp3',
  './MP3/Pecanhead/DX DONT GIVE A FK.mp3',
  './MP3/Pecanhead/dx thats what he said.mp3',
  './MP3/Pecanhead/DX WH THE FK.mp3',
  './MP3/Pecanhead/error_CDOxCYm.mp3',
  './MP3/Pecanhead/fat ass.mp3',
  './MP3/Pecanhead/fax.mp3',
  './MP3/Pecanhead/Frank Rizzo open ur ears.mp3',
  './MP3/Pecanhead/freezer.mp3',
  './MP3/Pecanhead/fuck_me_daddy_sick_dropgrabvidtomp3 mp3cut.mp3',
  './MP3/Pecanhead/full extension.mp3',
  './MP3/Pecanhead/geek squad.mp3',
  './MP3/Pecanhead/get on your knees.mp3',
  './MP3/Pecanhead/GET YOUR FAT ASS BACK HERE   AUDIO FROM JAYUZUMI.COM.mp3',
  './MP3/Pecanhead/go ahead please.mp3',
  './MP3/Pecanhead/guess who.mp3',
  './MP3/Pecanhead/guru.mp3',
  './MP3/Pecanhead/h0.mp3',
  './MP3/Pecanhead/h1.mp3',
  './MP3/Pecanhead/h2.mp3',
  './MP3/Pecanhead/h3.mp3',
  './MP3/Pecanhead/h4.mp3',
  './MP3/Pecanhead/h5.mp3',
  './MP3/Pecanhead/h6.mp3',
  './MP3/Pecanhead/h7.mp3',
  './MP3/Pecanhead/h8.mp3',
  './MP3/Pecanhead/h9.mp3',
  './MP3/Pecanhead/HE LOOK LIKE A MAN.mp3',
  './MP3/Pecanhead/hes a piece of shit.mp3',
  './MP3/Pecanhead/hi mam.mp3',
  './MP3/Pecanhead/hi sir.mp3',
  './MP3/Pecanhead/HINDI1.mp3',
  './MP3/Pecanhead/how do you say the flapjack.mp3',
  './MP3/Pecanhead/i dont wear underwear.mp3',
  './MP3/Pecanhead/i knew i was going to become a tranny.mp3',
  './MP3/Pecanhead/i like rape.mp3',
  './MP3/Pecanhead/I WANT TO TALK TO A MANAGER.mp3',
  './MP3/Pecanhead/ill be the best sex you will ever have.mp3',
  './MP3/Pecanhead/im bored and horny.mp3',
  './MP3/Pecanhead/im gonna lick you.mp3',
  './MP3/Pecanhead/im sitting and smoking and watching television.mp3',
  './MP3/Pecanhead/im sorry.mp3',
  './MP3/Pecanhead/laugh1.mp3',
  './MP3/Pecanhead/let it go.mp3',
  './MP3/Pecanhead/like popsicles.mp3',
  './MP3/Pecanhead/mad.mp3',
  './MP3/Pecanhead/mrs swan hello.mp3',
  './MP3/Pecanhead/Ms Swan at Halloween.mp3',
  './MP3/Pecanhead/my cock.mp3',
  './MP3/Pecanhead/nikad sexy.mp3',
  './MP3/Pecanhead/NO SWANN.mp3',
  './MP3/Pecanhead/oh my god.mp3',
  './MP3/Pecanhead/OH THANKS GUY.mp3',
  './MP3/Pecanhead/oh that felt good.mp3',
  './MP3/Pecanhead/OK OK I TELL U.mp3',
  './MP3/Pecanhead/ozzy show us youir cock.mp3',
  './MP3/Pecanhead/peachesnew.mp3',
  './MP3/Pecanhead/piss me off.mp3',
  './MP3/Pecanhead/pistol sound effect_zejYI9w.mp3',
  './MP3/Pecanhead/Police Academy   The Blue Oyster Bar Song.mp3',
  './MP3/Pecanhead/right thats correct.mp3',
  './MP3/Pecanhead/scammer intro microsoft.mp3',
  './MP3/Pecanhead/scammer intro.mp3',
  './MP3/Pecanhead/shit in the laundry.mp3',
  './MP3/Pecanhead/slap you.mp3',
  './MP3/Pecanhead/slinky dinky doo.mp3',
  './MP3/Pecanhead/song i know what boys like.mp3',
  './MP3/Pecanhead/song time of my life.mp3',
  './MP3/Pecanhead/sonic curses.mp3',
  './MP3/Pecanhead/sound fail fallo.mp3',
  './MP3/Pecanhead/south of the border i think they say.mp3',
  './MP3/Pecanhead/stone i suck dick.mp3',
  './MP3/Pecanhead/stone ima transsexual.mp3',
  './MP3/Pecanhead/stupid asshle.mp3',
  './MP3/Pecanhead/swann OK.mp3',
  './MP3/Pecanhead/Takes Scumbag.mp3',
  './MP3/Pecanhead/taser gun electric clicking zaps sparks 2.mp3',
  './MP3/Pecanhead/taser gun electric clicking zaps sparks 5.mp3',
  './MP3/Pecanhead/thats not in his mouth.mp3',
  './MP3/Pecanhead/THATS WH HE SAID DX.mp3',
  './MP3/Pecanhead/the price is right losing horn.mp3',
  './MP3/Pecanhead/This is Frank Rizzo.mp3',
  './MP3/Pecanhead/titanic parody mp3cut.mp3',
  './MP3/Pecanhead/TOUGHY.mp3',
  './MP3/Pecanhead/tylenol.mp3',
  './MP3/Pecanhead/u MF.mp3',
  './MP3/Pecanhead/u MFer 2.mp3',
  './MP3/Pecanhead/u sob asshole.mp3',
  './MP3/Pecanhead/up the fucking ass_OcRd90h.mp3',
  './MP3/Pecanhead/veryloudairhorn.mp3',
  './MP3/Pecanhead/what sort of bird feet do you have.mp3',
  './MP3/Pecanhead/whata sweetheart.mp3',
  './MP3/Pecanhead/where are you.mp3',
  './MP3/Pecanhead/whip his balls out.mp3',
  './MP3/Pecanhead/who the hell are you.mp3',
  './MP3/Pecanhead/why have launches.mp3',
  './MP3/Pecanhead/why you hanging up on me sir.mp3',
  './MP3/Pecanhead/would you ever try anal.mp3',
  './MP3/Pecanhead/yes thats right thats correct.mp3',
  './MP3/Pecanhead/Ylvis   The Fox (What Does The Fox Say) [Official music video HD].mp3',
  './MP3/Pecanhead/you asshole SOB.mp3',
  './MP3/Pecanhead/you know taco bell.mp3',
  './MP3/Pecanhead/you know what im saying.mp3',
  './MP3/Pecanhead/you like doggy.mp3',
  './MP3/Pecanhead/you sob.mp3',
  './MP3/Pecanhead/your neighbor or your friends or maybe relatives would have these things for you to see them.mp3',
  './MP3/Pecanhead/youre a filthy woman.mp3',
];

soundboards.swearing_Indian_Rex_Collection = [
  './MP3/Swearing_indian/Abola Muderchod.mp3',
  './MP3/Swearing_indian/Angery American Man Enjoy making harassment phone calls dont call again.mp3',
  './MP3/Swearing_indian/are you calling me by using a cellphone.mp3',
  './MP3/Swearing_indian/can you please hang up this call from your side sir.mp3',
  './MP3/Swearing_indian/do not ever call okay.mp3',
  './MP3/Swearing_indian/Do you know I am your father.mp3',
  './MP3/Swearing_indian/Do you want to book TicKit x2 TiKiTTiKiTTiKiTTiKiT.mp3',
  './MP3/Swearing_indian/fucking ass hole hindi insults.mp3',
  './MP3/Swearing_indian/Fuck yooooooooou fuck you.mp3',
  './MP3/Swearing_indian/fuck you sir fuck you.mp3',
  './MP3/Swearing_indian/fuuuck off bloody bitch.mp3',
  './MP3/Swearing_indian/get lost from here just get lost.mp3',
  './MP3/Swearing_indian/go and fuck yourself.mp3',
  './MP3/Swearing_indian/hello you mogichod.mp3',
  './MP3/Swearing_indian/how about you let me fuck your daughter and you watch me.mp3',
  './MP3/Swearing_indian/if you want may dick i will give you my dick.mp3',
  './MP3/Swearing_indian/im going to put a popup in ur daughter pussy then i will fix it tonight.mp3',
  './MP3/Swearing_indian/im gonna suck it yes.mp3',
  './MP3/Swearing_indian/im pretty sure youre mentally unstable.mp3',
  './MP3/Swearing_indian/indian scammer insults.mp3',
  './MP3/Swearing_indian/In order todo this first I need to fuck your mom okay.mp3',
  './MP3/Swearing_indian/in your ass i will give you my dick rather than macafeee.mp3',
  './MP3/Swearing_indian/i dont give a damn shit.mp3',
  './MP3/Swearing_indian/i have a dick give your dad mom son ill fuck your familly one by one.mp3',
  './MP3/Swearing_indian/I love techno trance.mp3',
  './MP3/Swearing_indian/I would love to be fucked in my ass.mp3',
  './MP3/Swearing_indian/Jamakin Insults.mp3',
  './MP3/Swearing_indian/jesus christ save me from you fuckers.mp3',
  './MP3/Swearing_indian/just your mom i guess.wav',
  './MP3/Swearing_indian/No no tickets available for you.mp3',
  './MP3/Swearing_indian/Oh that great you can publish that on bbc news.mp3',
  './MP3/Swearing_indian/oh wow wow omg oh wow.mp3',
  './MP3/Swearing_indian/oh your dick in stuck in your friends ass omg your are both doing sex your are doing sex omg.mp3',
  './MP3/Swearing_indian/okaaay you want macafee in my ass okay.mp3',
  './MP3/Swearing_indian/okay so that means you want my dick right.mp3',
  './MP3/Swearing_indian/OMG does he have cancer.mp3',
  './MP3/Swearing_indian/omg your computers got fucked and what about you.mp3',
  './MP3/Swearing_indian/ORB As Prank 1.mp3',
  './MP3/Swearing_indian/ORB As Prank 2.mp3',
  './MP3/Swearing_indian/ORB As Prank 3.mp3',
  './MP3/Swearing_indian/Paypal Paul.mp3',
  './MP3/Swearing_indian/please press 2 to fuck your girl fiend.mp3',
  './MP3/Swearing_indian/rundi lost mind.mp3',
  './MP3/Swearing_indian/senior supervisor fucking your mom and daughter together.mp3',
  './MP3/Swearing_indian/so as i understood that your are a mother fucker your fuck your own mother and you have a sister too click.mp3',
  './MP3/Swearing_indian/so he has cancer in his ass my god and you got cancer in your balls.mp3',
  './MP3/Swearing_indian/so how about you just go ahead and cuck my cock.mp3',
  './MP3/Swearing_indian/so if you are a gay just be proud that you are a gay.mp3',
  './MP3/Swearing_indian/Stop wasting my time you assholes.mp3',
  './MP3/Swearing_indian/what exactly are you trying to doing x2.mp3',
  './MP3/Swearing_indian/Your brother is what gay.mp3',
  './MP3/Swearing_indian/Your computer is going to be fucked got it.mp3',
  './MP3/Swearing_indian/you bloody bitch.mp3',
  './MP3/Swearing_indian/you dont have you email phone name and you calling to find where your macafee.mp3',
  './MP3/Swearing_indian/you have no job i know that.mp3',
  './MP3/Swearing_indian/are you trying to steal the prize.mp3',
  './MP3/Swearing_indian/batty boy.mp3',
  './MP3/Swearing_indian/Cindy possible pch victim voice mail.mp3',
  './MP3/Swearing_indian/cindy youre gonna be a dead bitch by the end of today.mp3',
  './MP3/Swearing_indian/fucking idiot.mp3',
  './MP3/Swearing_indian/have a good day imma be busy trying to get a hold of your guys mom.mp3',
  './MP3/Swearing_indian/hello is it me youre looking for i can see it in your eyes ah battey boy go suck yr muda.mp3',
  './MP3/Swearing_indian/horaaay.mp3',
  './MP3/Swearing_indian/how do you feel to know your a winner.mp3',
  './MP3/Swearing_indian/i said fuck you you fucking whore.mp3',
  './MP3/Swearing_indian/oh ya.mp3',
  './MP3/Swearing_indian/so you should such a stupid just hang up the phone call.mp3',
  './MP3/Swearing_indian/teri maka bola bencalode.mp3',
  './MP3/Swearing_indian/yah fuck you bro fuck you too fuck you hard.mp3',
  './MP3/Swearing_indian/yes im watching you though my crystal ball.mp3',
  './MP3/Swearing_indian/yes same as you i hope you can ask your muder about it.mp3',
  './MP3/Swearing_indian/you answered your self you ask you question to your self that you are a stupid and you answer yah you are de stupid.mp3',
  './MP3/Swearing_indian/you know you a maderchod.mp3',
  './MP3/Swearing_indian/your a fucking idiot.mp3',
  './MP3/Swearing_indian/Angelus 793.MP3',
  './MP3/Swearing_indian/Angelus a one time key 112169.MP3',
  './MP3/Swearing_indian/Angelus Alright.MP3',
  './MP3/Swearing_indian/Angelus and dont release it hold it down.MP3',
  './MP3/Swearing_indian/Angelus and from other finger press.MP3',
  './MP3/Swearing_indian/Angelus and now hold it down.MP3',
  './MP3/Swearing_indian/Angelus But before that.MP3',
  './MP3/Swearing_indian/Angelus Can you please confirm one thing for your safety.MP3',
  './MP3/Swearing_indian/Angelus can you please spell it out i explore.MP3',
  './MP3/Swearing_indian/Angelus can you please spell it out.MP3',
  './MP3/Swearing_indian/Angelus can you repeat word for word what you have written.MP3',
  './MP3/Swearing_indian/Angelus can you see something now.MP3',
  './MP3/Swearing_indian/Angelus can you seee my mouse moving.MP3',
  './MP3/Swearing_indian/Angelus Certified Technician for the windows.MP3',
  './MP3/Swearing_indian/Angelus Check all issues in exact manner.MP3',
  './MP3/Swearing_indian/Angelus click on connect.MP3',
  './MP3/Swearing_indian/Angelus click on it one more time click enter.MP3',
  './MP3/Swearing_indian/Angelus congratulations sir we are connected.MP3',
  './MP3/Swearing_indian/Angelus dont release it.MP3',
  './MP3/Swearing_indian/Angelus four boxes like windows.MP3',
  './MP3/Swearing_indian/Angelus four flags on the left bottom corner.MP3',
  './MP3/Swearing_indian/Angelus Gimme one second.MP3',
  './MP3/Swearing_indian/Angelus Hackers from Jordan and Turkey.MP3',
  './MP3/Swearing_indian/Angelus Hold it down.MP3',
  './MP3/Swearing_indian/Angelus I explore mp3.WAV',
  './MP3/Swearing_indian/Angelus I explore.MP3',
  './MP3/Swearing_indian/Angelus I think you not doing it the right way.MP3',
  './MP3/Swearing_indian/Angelus it says NOTEPAD mp3.WAV',
  './MP3/Swearing_indian/Angelus it says NOTEPAD.MP3',
  './MP3/Swearing_indian/Angelus Mr Robert Mr Bob.MP3',
  './MP3/Swearing_indian/Angelus not forward slash.MP3',
  './MP3/Swearing_indian/Angelus now leave your mouse.MP3',
  './MP3/Swearing_indian/Angelus now type over there let me get the key for you.MP3',
  './MP3/Swearing_indian/Angelus on the right bottom can you see certified support.MP3',
  './MP3/Swearing_indian/Angelus option of run.MP3',
  './MP3/Swearing_indian/Angelus option of YES.MP3',
  './MP3/Swearing_indian/Angelus Press the four flags key.MP3',
  './MP3/Swearing_indian/Angelus Right 6.mp3',
  './MP3/Swearing_indian/Angelus Right.MP3',
  './MP3/Swearing_indian/Angelus shortly notification click it.MP3',
  './MP3/Swearing_indian/Angelus shortly notification click it1.MP3',
  './MP3/Swearing_indian/Angelus space mp3.WAV',
  './MP3/Swearing_indian/Angelus Tanks for holdin the line can you hear me.MP3',
  './MP3/Swearing_indian/Angelus thats the right place sir click on it.MP3',
  './MP3/Swearing_indian/Angelus THE four flags key.MP3',
  './MP3/Swearing_indian/Angelus The reason you are talkin to me right now.MP3',
  './MP3/Swearing_indian/Angelus Till this problem is not fixed.MP3',
  './MP3/Swearing_indian/Angelus uh huh.MP3',
  './MP3/Swearing_indian/Angelus warning alert loop.MP3',
  './MP3/Swearing_indian/Angelus warning alert loop48kHz.WAV',
  './MP3/Swearing_indian/Angelus we are going to help you.MP3',
  './MP3/Swearing_indian/Angelus when you see option at bottom click on save.MP3',
  './MP3/Swearing_indian/Angelus who is this.mp3',
  './MP3/Swearing_indian/Angelus WHY YOU SUCH A DICKHEAD.mp3',
  './MP3/Swearing_indian/Angelus yes i can hear you.mp3',
  './MP3/Swearing_indian/Angelus yes.mp3',
  './MP3/Swearing_indian/Angelus yes1.mp3',
  './MP3/Swearing_indian/Angelus you callin from Michigan.MP3',
  './MP3/Swearing_indian/Angelus You dont need to worry.MP3',
  './MP3/Swearing_indian/Angelus you know boogeyman.mp3',
  './MP3/Swearing_indian/Angelus you want me to fuck your mother.mp3',
  './MP3/Swearing_indian/Angelus YOUR MOTHER WITHOUT CONDOMN.mp3',
  './MP3/Swearing_indian/Angelus on the right bottom the cor-ner.MP3',
  './MP3/Swearing_indian/family motto.mp3',
  './MP3/Swearing_indian/OOOOhYAAAAscammer.wav',
  './MP3/Swearing_indian/hold on x3 give me a moment.mp3',
  './MP3/Swearing_indian/sir it is very tiny.mp3',
  './MP3/Swearing_indian/that heckers want to smell your network.mp3',
  './MP3/Swearing_indian/the hackers want to smell your network and with the help of the smelling they are attracted - they are stealing your financial data.mp3',
  './MP3/Swearing_indian/there are some russian hackers which is connected with you.mp3',
  './MP3/Swearing_indian/yeees yes.mp3',
  './MP3/Swearing_indian/you are asking me what is 783 - thats your mothers pussy code.mp3',
  './MP3/Swearing_indian/i think you are heigh bro.mp3',
  './MP3/Swearing_indian/ill just pull your hair and put you mouth down to your own dick and make you suck it okay.mp3',
  './MP3/Swearing_indian/is this sound is coming from your asshole you motherfucker.mp3',
  './MP3/Swearing_indian/motherfucker.mp3',
  './MP3/Swearing_indian/oh you want to gang bang her.mp3',
  './MP3/Swearing_indian/or you want me to help you out.mp3',
  './MP3/Swearing_indian/so why the fucking you call on this number you fucking ass hole.mp3',
  './MP3/Swearing_indian/suck my dick you motherfucker.mp3',
  './MP3/Swearing_indian/suck your own dick you know how todo it.mp3',
  './MP3/Swearing_indian/teri maka bosada muderchod - hut.mp3',
  './MP3/Swearing_indian/you mother fucker.mp3',
  './MP3/Swearing_indian/MadFemaleScammer YouMothaFucka.mp3',
  './MP3/Swearing_indian/right sir.mp3',
  './MP3/Swearing_indian/scammer breakdown p1.mp3',
  './MP3/Swearing_indian/scammer breakdown p2.mp3',
  './MP3/Swearing_indian/welcom to the playstation stuuport how to i help you.mp3',
  './MP3/Swearing_indian/bark like a dog - bark x3 - bark like a dog x2.mp3',
  './MP3/Swearing_indian/can you see my cock - you like to suck it.mp3',
  './MP3/Swearing_indian/can you send me your dirty x4 panties.mp3',
  './MP3/Swearing_indian/did you like to drink my cum.mp3',
  './MP3/Swearing_indian/do you know what are the components of a computer - ohh i know cuz you dont even have a computer - your a poor guy.mp3',
  './MP3/Swearing_indian/do you think that we are fool here.mp3',
  './MP3/Swearing_indian/donald trump is my father.mp3',
  './MP3/Swearing_indian/dont tech your dad how to fuck.mp3',
  './MP3/Swearing_indian/even i have a left and a right balls buddy - do you have a left and right.mp3',
  './MP3/Swearing_indian/first of all mind your language.mp3',
  './MP3/Swearing_indian/fuck off - fuck your mother.mp3',
  './MP3/Swearing_indian/fuck off bitch and suck your mother.mp3',
  './MP3/Swearing_indian/fuck off you mother fucker.mp3',
  './MP3/Swearing_indian/get lost you mother fucker.mp3',
  './MP3/Swearing_indian/hey shut up you mother fuckers.mp3',
  './MP3/Swearing_indian/hindi insults 2.mp3',
  './MP3/Swearing_indian/hindi insults 3.mp3',
  './MP3/Swearing_indian/hindi insults 4.mp3',
  './MP3/Swearing_indian/hindi insults.mp3',
  './MP3/Swearing_indian/how are you.mp3',
  './MP3/Swearing_indian/how did it explode again.mp3',
  './MP3/Swearing_indian/how you doing - my dick is waiting for you.mp3',
  './MP3/Swearing_indian/i miss my son all the time my son i miss you all the time i know i do some bad things with your mom.mp3',
  './MP3/Swearing_indian/i would be on time everyday x2 sir.mp3',
  './MP3/Swearing_indian/ill give you one rupee hard cash - come - come and meet me some day.mp3',
  './MP3/Swearing_indian/im coming to you home and i will fuck your mother right now okay.mp3',
  './MP3/Swearing_indian/im fine habibi how about you.mp3',
  './MP3/Swearing_indian/im not here to listen all this crap for you.mp3',
  './MP3/Swearing_indian/joe biden is my uncle.mp3',
  './MP3/Swearing_indian/joe biden its my uncle why dont you understand.mp3',
  './MP3/Swearing_indian/just give me your credit card numbers.mp3',
  './MP3/Swearing_indian/let me tell you that maki choot is the eatable things.mp3',
  './MP3/Swearing_indian/macaroni and the cheese virus.mp3',
  './MP3/Swearing_indian/no x3 is that that its your mothersawhore dot com.mp3',
  './MP3/Swearing_indian/no you do one thing sir do you have a windows near by you - first you need to bang your computer on the floor and after throw it away from your windows simple as that - can you do that.mp3',
  './MP3/Swearing_indian/oh well on the bright side you wont need a hammer of a nail you can just use your sons head.mp3',
  './MP3/Swearing_indian/oh you are a gay - right.mp3',
  './MP3/Swearing_indian/ohh my god thank you.mp3',
  './MP3/Swearing_indian/ohh so that mean that your mother was a hoe.mp3',
  './MP3/Swearing_indian/okay i have to go i have a meeting with the donald trump right now.mp3',
  './MP3/Swearing_indian/okay im ready to marry you.mp3',
  './MP3/Swearing_indian/on its stuck up your ass you said - how did it get up your ass - you did a trick shot or something.mp3',
  './MP3/Swearing_indian/or you can suck my balls right now here.mp3',
  './MP3/Swearing_indian/scammer laughing 2.mp3',
  './MP3/Swearing_indian/scammer laughing.mp3',
  './MP3/Swearing_indian/scammer rap 1.mp3',
  './MP3/Swearing_indian/scammer rap 2.mp3',
  './MP3/Swearing_indian/scammer rap 3.mp3',
  './MP3/Swearing_indian/scammer sings i want to break free.mp3',
  './MP3/Swearing_indian/shut up and bend over.mp3',
  './MP3/Swearing_indian/sir i would really appreciate if you could go ahead and speak to me in the proper way - okay - if not i would have to go ahead and disconnect the call.mp3',
  './MP3/Swearing_indian/sir what is the concern you have called us for what reason you have called us today.mp3',
  './MP3/Swearing_indian/sir your voice is breaking could you please repeaty that and speak lounder.mp3',
  './MP3/Swearing_indian/smell it x2 smell my ass comon.mp3',
  './MP3/Swearing_indian/tera maka bola.mp3',
  './MP3/Swearing_indian/teri behnki choot rundike.mp3',
  './MP3/Swearing_indian/that what your mother said to me.mp3',
  './MP3/Swearing_indian/uh i will go and let you know the little recipe about a shrimp virus - are you here to listen that.mp3',
  './MP3/Swearing_indian/what you have todo is put some oil on your ass and put some shrimps in-between that thats the recipe.mp3',
  './MP3/Swearing_indian/why are you making prank calls hang up.mp3',
  './MP3/Swearing_indian/why dont you give me a job to fuck your mama.mp3',
  './MP3/Swearing_indian/yes hi whats up.mp3',
  './MP3/Swearing_indian/you are pretending to be oversmart but i know each and everything.mp3',
  './MP3/Swearing_indian/you are so funny man you are really so funny.mp3',
  './MP3/Swearing_indian/you bloody asshole then why did you give us call.mp3',
  './MP3/Swearing_indian/you have to try a little more harder buddy.mp3',
  './MP3/Swearing_indian/you mother fucker you call me dont call me alright.mp3',
  './MP3/Swearing_indian/you want baby - if you want baby tell me and i can give you baby.mp3',
  './MP3/Swearing_indian/you want to be my habibi.mp3',
  './MP3/Swearing_indian/ah wah-ah wah.mp3',
  './MP3/Swearing_indian/and im the executive here.mp3',
  './MP3/Swearing_indian/chicken burger 1.mp3',
  './MP3/Swearing_indian/chicken burger 2.mp3',
  './MP3/Swearing_indian/chicken burger disconnected.mp3',
  './MP3/Swearing_indian/chicken burger x3.mp3',
  './MP3/Swearing_indian/come to paris.mp3',
  './MP3/Swearing_indian/egg and toast - same x4.mp3',
  './MP3/Swearing_indian/fries coke fanter.mp3',
  './MP3/Swearing_indian/how are you brother how are you.mp3',
  './MP3/Swearing_indian/how may i help you sir.mp3',
  './MP3/Swearing_indian/my name is sam.mp3',
  './MP3/Swearing_indian/okay we are going to block your number dont call here again and again bye bye.mp3',
  './MP3/Swearing_indian/sir what you had in your breakfast.mp3',
  './MP3/Swearing_indian/sir you can simply concern with me like right.mp3',
  './MP3/Swearing_indian/technician disconnected.mp3',
  './MP3/Swearing_indian/that for connecting with geek squad this is allex william how are you doing today.mp3',
  './MP3/Swearing_indian/that you for calling support how may i help you.mp3',
  './MP3/Swearing_indian/uh hu.mp3',
  './MP3/Swearing_indian/unintelligible sounds.mp3',
  './MP3/Swearing_indian/what the problem you have sir - you can simply concern with me.mp3',
  './MP3/Swearing_indian/what.mp3',
  './MP3/Swearing_indian/yes (1).mp3',
  './MP3/Swearing_indian/you want to speak with my manager.mp3',
  './MP3/Swearing_indian/are you alright.mp3',
  './MP3/Swearing_indian/are you fool.mp3',
  './MP3/Swearing_indian/are you on a drugs right now.mp3',
  './MP3/Swearing_indian/are you out of the mind.mp3',
  './MP3/Swearing_indian/are you sick sir.mp3',
  './MP3/Swearing_indian/ask your mom to come and give me a blowjob.mp3',
  './MP3/Swearing_indian/do i have to call 911.mp3',
  './MP3/Swearing_indian/i am telling you what is the truth if you want to belive it or not its up to you.mp3',
  './MP3/Swearing_indian/its up to you im not forcing you to belive anything.mp3',
  './MP3/Swearing_indian/just shutup you big dumb asshole you mother fucker.mp3',
  './MP3/Swearing_indian/okay first of all be calm and explain me - which of problem you have on your computer right now.mp3',
  './MP3/Swearing_indian/okay we are just going to hang up that call and also we are going to block your number byby.mp3',
  './MP3/Swearing_indian/we dont want your target giftcard - if you want to offer something you can offer your pussy bitch.mp3',
];

soundboards.Sound_effect_1 = [
  './MP3/Sound_Effect_1/Sound Effect ambient crowd noise a crowded mall 1 hour.mp3',
  './MP3/Sound_Effect_1/Sound Effect footsteps heels on the pavement walking sound effect heels 1 hour pick relax.mp3',
  './MP3/Sound_Effect_1/Shopping Sound Effect.mp3',
  './MP3/Sound_Effect_1/Shopping Centre.mp3',
  './MP3/Sound_Effect_1/sneaker shoe on concrete floor fast pace.mp3',
  './MP3/Sound_Effect_1/sneaker shoe on concrete floor medium pace.mp3',
  './MP3/Sound_Effect_1/sneaker shoe on concrete floor slow pace 1.mp3',
  './MP3/Sound_Effect_1/sneaker shoe on concrete floor slow pace 2.mp3',
  './MP3/Sound_Effect_1/walmart checkout sfx.mp3',
  './MP3/Sound_Effect_1/StoreClerk.mp3',
  './MP3/Sound_Effect_1/Paying 4 Products.mp3',
  './MP3/Sound_Effect_1/manual banknote counting.mp3',
  './MP3/Sound_Effect_1/Mobile Phone Ringtone.mp3',
  './MP3/Sound_Effect_1/doorbell.mp3',
  './MP3/Sound_Effect_1/keys on door and open.mp3',
  './MP3/Sound_Effect_1/door open close.mp3',
  './MP3/Sound_Effect_1/C&C Generals - Worker Audio.mp3',
];

soundboards.Soundboard1 = [
  './MP3/SB/acrow.mp3',
  './MP3/SB/alert microsoft.mp3',
  './MP3/SB/A Fake Microsoft Popup.mp3',
  './MP3/SB/A Fake Popup.mp3',
  './MP3/SB/annoying.mp3',
  './MP3/SB/bbb.mp3',
  './MP3/SB/bear2.mp3',
  './MP3/SB/bell Copy Copy.mp3',
  './MP3/SB/bell Copy.mp3',
  './MP3/SB/bell.mp3',
  './MP3/SB/BELLA.mp3',
  './MP3/SB/Bhenchod Song.mp3',
  './MP3/SB/boathorn.mp3',
  './MP3/SB/boreworms.mp3',
  './MP3/SB/BritMonkey.mp3',
  './MP3/SB/brrruuuuuhhh.mp3',
  './MP3/SB/Burp3.mp3',
  './MP3/SB/busted.mp3',
  './MP3/SB/car crash.mp3',
  './MP3/SB/crowdwow.mp3',
  './MP3/SB/cryingbaby.mp3',
  './MP3/SB/curbyourscamming.mp3',
  './MP3/SB/dagnammit.mp3',
  './MP3/SB/dan whats wrong with you.mp3',
  './MP3/SB/donkey.mp3',
  './MP3/SB/dubludublu.mp3',
  './MP3/SB/evillaugh.mp3',
  './MP3/SB/fart.mp3',
  './MP3/SB/fart2.mp3',
  './MP3/SB/fastphone.mp3',
  './MP3/SB/FBI.mp3',
  './MP3/SB/flashiloveyou.mp3',
  './MP3/SB/free robuk 1.mp3',
  './MP3/SB/frog1.mp3',
  './MP3/SB/german1.mp3',
  './MP3/SB/german2.mp3',
  './MP3/SB/german3.mp3',
  './MP3/SB/givedogahug.mp3',
  './MP3/SB/goat.mp3',
  './MP3/SB/google.mp3',
  './MP3/SB/hello.mp3',
  './MP3/SB/hellomichelle.mp3',
  './MP3/SB/HindiMale1.mp3',
  './MP3/SB/honk.mp3',
  './MP3/SB/horse1.mp3',
  './MP3/SB/howl.mp3',
  './MP3/SB/idoneditit.mp3',
  './MP3/SB/jerkoff.mp3',
  './MP3/SB/khan.mp3',
  './MP3/SB/klaxon.mp3',
  './MP3/SB/laugh.mp3',
  './MP3/SB/laugh3.mp3',
  './MP3/SB/laughserious.mp3',
  './MP3/SB/lipsmacking.mp3',
  './MP3/SB/listentome.mp3',
  './MP3/SB/LoudBirds.mp3',
  './MP3/SB/motherlessgoat.mp3',
  './MP3/SB/nerfherder.mp3',
  './MP3/SB/nokia.mp3',
  './MP3/SB/on fire.mp3',
  './MP3/SB/open fire.mp3',
  './MP3/SB/oz.mp3',
  './MP3/SB/piercingscream.mp3',
  './MP3/SB/pig1.mp3',
  './MP3/SB/playlikegirl.mp3',
  './MP3/SB/PoorKitty.mp3',
  './MP3/SB/popsicle.mp3',
  './MP3/SB/riper.mp3',
  './MP3/SB/rooster crow.mp3',
  './MP3/SB/scream.mp3',
  './MP3/SB/scream2.mp3',
  './MP3/SB/siren.mp3',
  './MP3/SB/swamp.mp3',
  './MP3/SB/terimaakichut.mp3',
  './MP3/SB/TOXIC FLUTE.mp3',
  './MP3/SB/trumpetwah.mp3',
  './MP3/SB/typersbusted.mp3',
  './MP3/SB/wasted.mp3',
  './MP3/SB/wildcat.mp3',
  './MP3/SB/yeehaw.mp3',
  './MP3/SB/you is a scammer.mp3',
  './MP3/SB/you smell.mp3',
];

soundboards.Soundboard2 = [
  './MP3/SB/angel dust aww harder daddy.mp3',
  './MP3/SB/angry4.mp3',
  './MP3/SB/are you serious right now.mp3',
  './MP3/SB/bababooey sound effect.mp3',
  './MP3/SB/badumtss.swf.mp3',
  './MP3/SB/batman on drugs 1.mp3',
  './MP3/SB/c4out4.mp3',
  './MP3/SB/chase.mp3',
  './MP3/SB/dank meme compilation volume 17 cutted.mp3',
  './MP3/SB/deja vu.mp3',
  './MP3/SB/derp 1.mp3',
  './MP3/SB/donald trump fake news sound effect.mp3',
  './MP3/SB/el risitas funniest laugh ever.mp3',
  './MP3/SB/emotional damage.mp3',
  './MP3/SB/nope.mp3',
  './MP3/SB/epic 17.mp3',
  './MP3/SB/fuck this shit im out.mp3',
  './MP3/SB/gayyy.mp3',
  './MP3/SB/get yo fat ass back here.mp3',
  './MP3/SB/goodbadugly whistle long.mp3',
  './MP3/SB/goofy ahhh.mp3',
  './MP3/SB/gunshot1 connor p 8650 hifi.mp3',
  './MP3/SB/hahahahihihihehehe.mp3',
  './MP3/SB/hello your computer has virus sound effect.mp3',
  './MP3/SB/hello its john cena.mp3',
  './MP3/SB/it was at this moment that he he knew he f cked up.mp3',
  './MP3/SB/jerry farts united clean loop original 3 48 hd.mp3',
  './MP3/SB/jettlastkill2.mp3',
  './MP3/SB/kreun.mp3',
  './MP3/SB/laugh funny lol.mp3',
  './MP3/SB/lets go car meme original clip.mp3',
  './MP3/SB/mcdonalds im lovin it jingle.mp3',
  './MP3/SB/movie 1.mp3',
  './MP3/SB/musica elevador short.mp3',
  './MP3/SB/ninja rages at kid sound effects.mp3',
  './MP3/SB/nooo.swf.mp3',
  './MP3/SB/oh my god they killed kenny.mp3',
  './MP3/SB/panjabi mc mundian to bach ke the dictator soundtrack 0s 7s.mp3',
  './MP3/SB/ringtone 7.mp3',
  './MP3/SB/run vine sound effect.mp3',
  './MP3/SB/scooby doo laugh sped up.mp3',
  './MP3/SB/screaming goat.mp3',
  './MP3/SB/shutup.swf.mp3',
  './MP3/SB/snore mimimimimimi.mp3',
  './MP3/SB/sound fail fallo.mp3',
  './MP3/SB/studio audience awwww sound fx.mp3',
  './MP3/SB/surprise motherfucker.mp3',
  './MP3/SB/sweet jesus mr herbert.mp3',
  './MP3/SB/taken i will find you and i will kill you hd.mp3',
  './MP3/SB/technical error.mp3',
  './MP3/SB/thisissparta.swf.mp3',
  './MP3/SB/trollolol.swf.mp3',
  './MP3/SB/wtf boom.mp3',
  './MP3/SB/y2mate.mp3',
  './MP3/SB/yeet sound effect.mp3',
  './MP3/SB/you are an idiot.mp3',
  './MP3/SB/crazy realistic knocking sound troll twitch streamers small.mp3',
  './MP3/SB/evillaugh.swf.mp3',
  './MP3/SB/gun reload sound effect.mp3',
  './MP3/SB/hello motherfucker.mp3',
  './MP3/SB/magicword.mp3',
  './MP3/SB/money 2.mp3',
  './MP3/SB/nein adolf.mp3',
  './MP3/SB/pirate of carbine Flute.mp3',
  './MP3/SB/shut the fuck up.mp3',
  './MP3/SB/spooky scary skeleton.mp3',
  './MP3/SB/windows 10 error sound.mp3',
];

soundboards.Sounds_Songs = [
  './MP3/Songs/ab bol na madarchod.mp3',
  './MP3/Songs/The Bhenchod Song.mp3',
  './MP3/Songs/Useless man song.mp3',
  './MP3/Songs/Useless Man.mp3',
  './MP3/Songs/We are Anonymous Intro HD.mp3',
  './MP3/Songs/virus song on computer.mp3',
];

soundboards.Ear_Raped = [
  './MP3/EAR_RAPED/Bagpipe Music (EAR RAPE).mp3',
  './MP3/EAR_RAPED/BARNEY THEME SONG (EAR RAPE) (BASS BOOSTED).mp3',
  './MP3/EAR_RAPED/Chinese rap meme  earrape (full music).mp3',
  './MP3/EAR_RAPED/Earrape Sound Effects (system startup sound effects).mp3',
  './MP3/EAR_RAPED/Emotional Titanic Flute (EAR RAPE).mp3',
  './MP3/EAR_RAPED/Fireman Sam Theme Song (Ear Rape).mp3',
  './MP3/EAR_RAPED/Illuminati song (Ear Rape)!!!.mp3',
  './MP3/EAR_RAPED/Krusty Crab Song Ear Rape.mp3',
  './MP3/EAR_RAPED/loud indian music.mp3',
  './MP3/EAR_RAPED/Monsters INC (EAR RAPE) [ 1 Hour Loop - Sleep Song ].mp3',
  './MP3/EAR_RAPED/PAW Patrol Theme Song Ear Rape.mp3',
  './MP3/EAR_RAPED/Rick Roll EARRAPE.mp3',
  './MP3/EAR_RAPED/Simpsons Theme Song! (EAR RAPE).mp3',
  './MP3/EAR_RAPED/Spongebob Ear Rape Song.mp3',
  './MP3/EAR_RAPED/SpongeBob theme song  Earrape.mp3',
  './MP3/EAR_RAPED/Thomas The Tank Engine Theme Song (Ear Rape).mp3',
  './MP3/EAR_RAPED/Titanic theme song  Ear Rape.mp3',
  './MP3/EAR_RAPED/Toy story theme (EAR RAPE).mp3',
];
