// effect audio group definitions
function create_effect_group(name, count) {
  var obj = {
    'name': name,
    'audio': [],
  };
  for (let i = 1; i <= count; i += 1) {
    obj.audio.push('./effects/' + name + ' ' + i.toString() + '.ogg');
  }
  return obj;
}
var effect_groups = {
  'arrow loose and hit': 7,
  'dirt slam': 4,
  'dragon bite': 2,
  'ooze': 5,
  'owlbear roar': 4,
  'slam attack': 4,
  'swimming': 6,
  'sword clash': 3,
  'thunder clap': 4,
  'wave crash': 4,
};
for (let name in effect_groups) {
  let count = effect_groups[name]
  effect_groups[name] = create_effect_group(name, count);
}


// Specific soundboards
var soundboards = {}
soundboards.Car = [
  './MP3/Car/car 0 fast 1 tm 6 complete.mp3',
  './MP3/Car/car 1 door open.mp3',
  './MP3/Car/car 2 door close.mp3',
  './MP3/Car/car 3 handbrake release.mp3',
  './MP3/Car/car 4 seat belt.mp3',
  './MP3/Car/car 5 key ignition insert.mp3',
  './MP3/Car/car 6 ignition.mp3',
  './MP3/Car/car 7 idle engine sound late evening 1 hour.mp3',
  './MP3/Car/car 8 driving 45 minetes.mp3',
  './MP3/Car/car turn signal.mp3',
  './MP3/Car/car window open.mp3',
  './MP3/Car/car seatbelt alarm.mp3',
  './MP3/Car/car horn sound effect 1.mp3',
  './MP3/Car/car horn sound effect 2.mp3',
  './MP3/Car/car horn traffic sound effect.mp3',
  './MP3/Car/car ambulance siren approach and drive by.mp3',
  './MP3/Car/car fire truck siren pass by.mp3',
  './MP3/Car/car police sirens passing by.mp3',
  './MP3/Car/car driving in the rain.mp3',
  './MP3/Car/8 hours of car driving sound effect   car sound effect   car driving sound and car noises.mp3',
  './MP3/Car/car passing.mp3',
  './MP3/Car/car radio los santos rock radio.mp3',
  './MP3/Car/car radio non stop pop radio.mp3',
  './MP3/Car/car radio rebel radio grand theft auto 5.mp3',
  './MP3/Car/car radio vinewood boulevard radio grand theft auto 5.mp3',
  './MP3/Car/car radio 10 grand thef tauto sanandreas.mp3',
];

soundboards.Store_Clerk = [
  './MP3/Store_Clerk/How muchts do you need.mp3',
  './MP3/Store_Clerk/we have a new policy about large transactions and will no longer be able to complete this order due to the suspicious nature i do truly apologize for the inconvenience.mp3',
  './MP3/Store_Clerk/i apologize for the inconvenience.mp3',
  './MP3/Store_Clerk/its for a party its for a family member that wont be anny issue.mp3',
  './MP3/Store_Clerk/oooo i see.mp3',
  './MP3/Store_Clerk/ok.mp3',
  './MP3/Store_Clerk/o that is allot.mp3',
  './MP3/Store_Clerk/bye now.mp3',
  './MP3/Store_Clerk/come back and see you soon.mp3',
  './MP3/Store_Clerk/hello Sir.mp3',
  './MP3/Store_Clerk/origth you have a  realy good day thank you.mp3',
  './MP3/Store_Clerk/that is fine can i m have you with somthing els.mp3',
];

soundboards.IRL_Rosie = [
./MP3/IRLRosie/hello this is microsoft fraid detector.mp3
./MP3/IRLRosie/to speak whit a repersenative press 2.mp3
];

soundboards.Paula_Twocockes = [
  './MP3/Paula/A as in Alfa.mp3',
  './MP3/Paula/B as in Bravo.mp3',
  './MP3/Paula/C as in Charlie.mp3',
  './MP3/Paula/D as in Delta.mp3',
  './MP3/Paula/E as in Echo.mp3',
  './MP3/Paula/F as in Foxtrot.mp3',
  './MP3/Paula/G as in Golf.mp3',
  './MP3/Paula/H as in Hotel.mp3',
  './MP3/Paula/I as in Indico.mp3',
  './MP3/Paula/J as in Juliett.mp3',
  './MP3/Paula/K as in Kilo.mp3',
  './MP3/Paula/L as in Lima.mp3',
  './MP3/Paula/M as in Mike.mp3',
  './MP3/Paula/N as in November.mp3',
  './MP3/Paula/O as in Oscar.mp3',
  './MP3/Paula/P as in Papa.mp3',
  './MP3/Paula/Q as in Quebec.mp3',
  './MP3/Paula/R as in Romeo.mp3',
  './MP3/Paula/S as in Sierra.mp3',
  './MP3/Paula/T as in Tango.mp3',
  './MP3/Paula/U as in Uniform.mp3',
  './MP3/Paula/V as in Victor.mp3',
  './MP3/Paula/W as in Whiskey.mp3',
  './MP3/Paula/X as in Xray.mp3',
  './MP3/Paula/Y as in Yankee.mp3',
  './MP3/Paula/Z as in Zulu.mp3',
  './MP3/Paula/A.mp3',
  './MP3/Paula/B.mp3',
  './MP3/Paula/C.mp3',
  './MP3/Paula/D.mp3',
  './MP3/Paula/E 1.mp3',
  './MP3/Paula/E 2.mp3',
  './MP3/Paula/F 1.mp3',
  './MP3/Paula/F 2.mp3',
  './MP3/Paula/G 1.mp3',
  './MP3/Paula/G 2.mp3',
  './MP3/Paula/H.mp3',
  './MP3/Paula/i 1.mp3',
  './MP3/Paula/i 2.mp3',
  './MP3/Paula/K 1.mp3',
  './MP3/Paula/K 2.mp3',
  './MP3/Paula/L.mp3',
  './MP3/Paula/M.mp3',
  './MP3/Paula/O.mp3',
  './MP3/Paula/P.mp3',
  './MP3/Paula/Q.mp3',
  './MP3/Paula/R.mp3',
  './MP3/Paula/S.mp3',
  './MP3/Paula/T.mp3',
  './MP3/Paula/U.mp3',
  './MP3/Paula/V.mp3',
  './MP3/Paula/W.mp3',
  './MP3/Paula/X.mp3',
  './MP3/Paula/Y.mp3',
  './MP3/Paula/10 minetes 1.mp3',
  './MP3/Paula/10 minetes 2.mp3',
  './MP3/Paula/15 minetes 1.mp3',
  './MP3/Paula/15 minetes 2.mp3',
  './MP3/Paula/20 minetes.mp3',
  './MP3/Paula/25 minetes.mp3',
  './MP3/Paula/30 minetes.mp3',
  './MP3/Paula/5 minetes 1.mp3',
  './MP3/Paula/5 minetes 2.mp3',
  './MP3/Paula/amazon gifcard.mp3',
  './MP3/Paula/Apple gifcard.mp3',
  './MP3/Paula/Applebees gifcard.mp3',
  './MP3/Paula/are you acting up like a Big one or like a little one.mp3',
  './MP3/Paula/are you lister to me.mp3',
  './MP3/Paula/belecove.mp3',
  './MP3/Paula/bette cove.mp3',
  './MP3/Paula/Bhenchot.mp3',
  './MP3/Paula/boy.mp3',
  './MP3/Paula/can you help me fixs it.mp3',
  './MP3/Paula/can you tell me what is wrong with myn accound.mp3',
  './MP3/Paula/Chase Bank bank.mp3',
  './MP3/Paula/Come here you little shit Dont make me tell you again.mp3',
  './MP3/Paula/damit why where calling me over and over again.mp3',
  './MP3/Paula/do the little baby do a popo in his pants do he need a daiper change.mp3',
  './MP3/Paula/do you need a bodle.mp3',
  './MP3/Paula/Do you need a daiper change.mp3',
  './MP3/Paula/Do you shit your pants.mp3',
  './MP3/Paula/do you understand the word that comes out off myn mount.mp3',
  './MP3/Paula/Do your need a blanket.mp3',
  './MP3/Paula/dot.mp3',
  './MP3/Paula/Double point.mp3',
  './MP3/Paula/English motherfucker do you speak it .mp3',
  './MP3/Paula/Get your ass over here.mp3',
  './MP3/Paula/Giftcard.mp3',
  './MP3/Paula/girl.mp3',
  './MP3/Paula/give me somebody else.mp3',
  './MP3/Paula/Good day 1.mp3',
  './MP3/Paula/Good day 2.mp3',
  './MP3/Paula/Google Giftcard.mp3',
  './MP3/Paula/google play card.mp3',
  './MP3/Paula/Google play gifcard.mp3',
  './MP3/Paula/hello 1.mp3',
  './MP3/Paula/hello 2.mp3',
  './MP3/Paula/hello are you there..mp3',
  './MP3/Paula/hello are you there.mp3',
  './MP3/Paula/hey pig man.mp3',
  './MP3/Paula/How can you help me.mp3',
  './MP3/Paula/How muchts.mp3',
  './MP3/Paula/i am at the PNC bank.mp3',
  './MP3/Paula/i am close to CVS .mp3',
  './MP3/Paula/i am close to Kroger.mp3',
  './MP3/Paula/i am close to Piggly wiggly 1.mp3',
  './MP3/Paula/i am close to Piggly wiggly 2.mp3',
  './MP3/Paula/i am close to walmart..mp3',
  './MP3/Paula/i am close to walmart.mp3',
  './MP3/Paula/i am get a error code on a game 3dtfm4d .mp3',
  './MP3/Paula/i am have a car.mp3',
  './MP3/Paula/i am there dont care.mp3',
  './MP3/Paula/i am watching movies on youtube.mp3',
  './MP3/Paula/i am watching pornhub.mp3',
  './MP3/Paula/i am with the Bank of America.mp3',
  './MP3/Paula/i am with the Chase Bank .mp3',
  './MP3/Paula/i can in the the car.mp3',
  './MP3/Paula/I do not see it.mp3',
  './MP3/Paula/i have a bank.mp3',
  './MP3/Paula/i have a paypal account.mp3',
  './MP3/Paula/i have download it.mp3',
  './MP3/Paula/i have more number then you mother have stds.mp3',
  './MP3/Paula/I have target cvs kroger walmart piggly wiggly all close to me.mp3',
  './MP3/Paula/I have.mp3',
  './MP3/Paula/i m looking at the screen rigth now.mp3',
  './MP3/Paula/i press install.mp3',
  './MP3/Paula/i press nexs.mp3',
  './MP3/Paula/I see my icons on my computer screen.mp3',
  './MP3/Paula/i see your bhenchot father on gb road last nigth.mp3',
  './MP3/Paula/i see your mother on GB road last night.mp3',
  './MP3/Paula/i think a hacker have hack in my paypal account.mp3',
  './MP3/Paula/i think a hacker have hack my account.mp3',
  './MP3/Paula/i was playing a game.mp3',
  './MP3/Paula/ill cannot upload a image on myn facebook.mp3',
  './MP3/Paula/ill got a broblume with myn computer.mp3',
  './MP3/Paula/ill have download anydesk.mp3',
  './MP3/Paula/ill have download connect wise.mp3',
  './MP3/Paula/ill have download Real vnc viewer.mp3',
  './MP3/Paula/ill have download screenconnect.mp3',
  './MP3/Paula/ill have download teamviewer.mp3',
  './MP3/Paula/ill have ultraviewer downloaded.mp3',
  './MP3/Paula/ill see a boxs say run.mp3',
  './MP3/Paula/ill see the run boxs.mp3',
  './MP3/Paula/ill will beath you ass like a drum if you dont get back to your room.mp3',
  './MP3/Paula/ip address.mp3',
  './MP3/Paula/is this amazon.mp3',
  './MP3/Paula/is this bestbuy.mp3',
  './MP3/Paula/is this facebook.mp3',
  './MP3/Paula/Is this irs.mp3',
  './MP3/Paula/is this Microsoft tech support.mp3',
  './MP3/Paula/is this online tech support.mp3',
  './MP3/Paula/is this paypal.mp3',
  './MP3/Paula/is this tech support.mp3',
  './MP3/Paula/Little baby boy.mp3',
  './MP3/Paula/little baby girl.mp3',
  './MP3/Paula/Lowes gifcard.mp3',
  './MP3/Paula/madam.mp3',
  './MP3/Paula/my paypal has a black hole when i put money its dispired.mp3',
  './MP3/Paula/myn firewall is disable for some reason.mp3',
  './MP3/Paula/myn mouse is not working.mp3',
  './MP3/Paula/myn printer is not working.mp3',
  './MP3/Paula/Myn screen is stuck.mp3',
  './MP3/Paula/network.mp3',
  './MP3/Paula/Nike gifcard .mp3',
  './MP3/Paula/och LOUD.mp3',
  './MP3/Paula/ok.mp3',
  './MP3/Paula/Oke doki.mp3',
  './MP3/Paula/oke.mp3',
  './MP3/Paula/okee.mp3',
  './MP3/Paula/PNC bank.mp3',
  './MP3/Paula/printer.mp3',
  './MP3/Paula/rigth.mp3',
  './MP3/Paula/rundi.mp3',
  './MP3/Paula/slash.mp3',
  './MP3/Paula/somboddy change myn password on myn facebook account.mp3',
  './MP3/Paula/somboddy have buy on myn accound a Phone.mp3',
  './MP3/Paula/some time myn letter change.mp3',
  './MP3/Paula/steam gifcard.mp3',
  './MP3/Paula/sumja Understand 1.mp3',
  './MP3/Paula/sumja Understand 2.mp3',
  './MP3/Paula/Sumja understand.mp3',
  './MP3/Paula/talking to you.mp3',
  './MP3/Paula/tell me.mp3',
  './MP3/Paula/that is not a virus.mp3',
  './MP3/Paula/the Bank of America,.mp3',
  './MP3/Paula/The best part is run to your mother legs Bhenchot.mp3',
  './MP3/Paula/The best part is run to your mother legs rundi.mp3',
  './MP3/Paula/the number is.mp3',
  './MP3/Paula/the password is.mp3',
  './MP3/Paula/there is no cure for it.mp3',
  './MP3/Paula/there is no cure for stopit.mp3',
  './MP3/Paula/there is not cure for stopit.mp3',
  './MP3/Paula/Understand Sumja.mp3',
  './MP3/Paula/vinalla cards.mp3',
  './MP3/Paula/walk.mp3',
  './MP3/Paula/Wells Fargo bank .mp3',
  './MP3/Paula/Wells Fargo bank.mp3',
  './MP3/Paula/what do i need to download.mp3',
  './MP3/Paula/what do you need.mp3',
  './MP3/Paula/what else should I see on my screen.mp3',
  './MP3/Paula/what gifcard do you need Google play Apple target vinalla cards Nike Lowes steam xbox Applebees amazon Best Buy.mp3',
  './MP3/Paula/what gift card do i need to buy.mp3',
  './MP3/Paula/what is wrong with myn router.mp3',
  './MP3/Paula/what is wrong with myn 1.mp3',
  './MP3/Paula/what is wrong with myn 2.mp3',
  './MP3/Paula/what now.mp3',
  './MP3/Paula/where you drop on your head at birth.mp3',
  './MP3/Paula/Why are you calling me.mp3',
  './MP3/Paula/why are you that stopit.mp3',
  './MP3/Paula/Why do i need to send you money .mp3',
  './MP3/Paula/Why do i need to send you money.mp3',
  './MP3/Paula/xbox gifcard.mp3',
  './MP3/Paula/you are a bhenchot.mp3',
  './MP3/Paula/you bedacove.mp3',
  './MP3/Paula/You born with it i cant help you.mp3',
  './MP3/Paula/you can go with your head between myn tieties anf go like.mp3',
  './MP3/Paula/you dont speak english.mp3',
  './MP3/Paula/You where calling me over and over.mp3',
  './MP3/Paula/your are a assholl.mp3',
  './MP3/Paula/your are in a time out.mp3',
  './MP3/Paula/your little baby need a baba.mp3',
  './MP3/Paula/Your little baby need a toy to play with.mp3',
];

soundboards.Child = [
  './MP3/child/ahh.ogg',
  './MP3/child/are we there yet.ogg',
  './MP3/child/can you help me with myn home work.ogg',
  './MP3/child/can i m have a snack.ogg',
  './MP3/child/can i m have some ice cream.ogg',
  './MP3/child/com doesend work.ogg',
  './MP3/child/computer is locked.ogg',
  './MP3/child/dad.ogg',
  './MP3/child/daddie.ogg',
  './MP3/child/daddy 1.ogg',
  './MP3/child/daddy 2.ogg',
  './MP3/child/Dont play game with me.ogg',
  './MP3/child/Giggle.ogg',
  './MP3/child/hello are you there.ogg',
  './MP3/child/hello i m talking.ogg',
  './MP3/child/i dont lie.ogg',
  './MP3/child/i m can read verry well.ogg',
  './MP3/child/i m click on it.ogg',
  './MP3/child/i m got a popup on myn computer.ogg',
  './MP3/child/i m have somthing the do.ogg',
  './MP3/child/i m life in the sewer  pipline.ogg',
  './MP3/child/i m live in the middle of nowhere.ogg',
  './MP3/child/i m never lie.ogg',
  './MP3/child/i m not a victum.ogg',
  './MP3/child/i m thirsty.ogg',
  './MP3/child/its install.ogg',
  './MP3/child/its not working.ogg',
  './MP3/child/listen to me.ogg',
  './MP3/child/lister to me.ogg',
  './MP3/child/look out.ogg',
  './MP3/child/mam 1.ogg',
  './MP3/child/mam 2.ogg',
  './MP3/child/mammie 1.ogg',
  './MP3/child/mammie 2.ogg',
  './MP3/child/my brother is theasing me.ogg',
  './MP3/child/my last name is oplichter.ogg',
  './MP3/child/myn brother broke myn toy.ogg',
  './MP3/child/myn fathert name is ben oplichter.ogg',
  './MP3/child/myn mom tells dont talk with strangers.ogg',
  './MP3/child/myn name is  sharon the miler.ogg',
  './MP3/child/myn name is laura.ogg',
  './MP3/child/no.ogg',
  './MP3/child/och everything is ok.ogg',
  './MP3/child/ok.ogg',
  './MP3/child/okee.ogg',
  './MP3/child/the wheel of the car is broken.ogg',
  './MP3/child/uhum.ogg',
  './MP3/child/what do i m need the do.ogg',
  './MP3/child/what is myn ip adderes.ogg',
  './MP3/child/all heil wob legend.ogg',
  './MP3/child/all heil the feret king.ogg',
  './MP3/child/who are you talking.ogg',
  './MP3/child/who are you.ogg',
  './MP3/child/who is on the phone.ogg',
  './MP3/child/yes i do.ogg',
  './MP3/child/yes.ogg',
];

soundboards.Annie = [
  './MP3/annie/0 Annie  Hello .m4a',
  './MP3/annie/1 Annie  Hello  2.m4a',
  './MP3/annie/10 Annie  I m Sorry What Did You Say  You Want My Phone Number .m4a',
  './MP3/annie/11 Annie  Yes My Phone Number Is .m4a',
  './MP3/annie/12 Annie  Well I m 82 I ll Be 83 In August .m4a',
  './MP3/annie/13 Annie  Yes  Yes That s Correct .m4a',
  './MP3/annie/14 Annie  Er Noo .m4a',
  './MP3/annie/15 Annie  Yes .m4a',
  './MP3/annie/16 Annie  Okay Yes I See That Yes .m4a',
  './MP3/annie/17 Annie  Okay Yes That s Fine .m4a',
  './MP3/annie/18 Annie  Ohh I Don t Know. I m Not To Sure .m4a',
  './MP3/annie/19 Annie  I m Sorry What Was That Sweetie .m4a',
  './MP3/annie/2 Annie  Hello  Hello Can You Hear Me .m4a',
  './MP3/annie/20 Annie  I m Sorry What Was That! .m4a',
  './MP3/annie/21 Annie  I Was Just Looking At My Emails .m4a',
  './MP3/annie/22 Annie  My Bank .m4a',
  './MP3/annie/22.Annie  Ye I Use Google Chrome .m4a',
  './MP3/annie/23 Annie  Yes At The Top Of The Page Yes .m4a',
  './MP3/annie/23. Annie  I Have Bank of America .m4a',
  './MP3/annie/24 Annie  It s Bank of America .m4a',
  './MP3/annie/25 Annie  No It s Not One Of Those s Mac Computers  It s A Windows Computer .m4a',
  './MP3/annie/26 Annie  Oh Noo I Have No Idea What Make Of This Computer Is  My Grandson Gave Me This Computer .m4a',
  './MP3/annie/27 Annie  Well I Wanted To Cancel Because I Don t You The Services  I Wanted To Get My Money Back .m4a',
  './MP3/annie/28 Annie  Oh So I Need To Fill Out Da Form .m4a',
  './MP3/annie/3 Annie  I m Sorry Your Phone Line Was Breaking Up  What Did You Say .m4a',
  './MP3/annie/4 Annie  Oh Sorry Yes I Can Hear You Know  I Don t Know What Happened  But Yes I Can Hear You Now .m4a',
  './MP3/annie/5 Annie  Yes My Name Is Annabelle But My Friends Call Me Annie ANNIE .m4a',
  './MP3/annie/6 Annie  Yes My Last Name Is Turd TURD .m4a',
  './MP3/annie/7 Annie  My Address Is .m4a',
  './MP3/annie/8 Annie  You Need My Date Of Birth .m4a',
  './MP3/annie/9 Annie  Date Of Birth .m4a',
  './MP3/annie/9. Annie  Email Address .m4a',
  './MP3/annie/Annie  Ah Ha Yes .m4a',
  './MP3/annie/Annie  Can You Wait While I Go And Get Myself A Glass Of Water .m4a',
  './MP3/annie/Annie  Erm Okay .m4a',
  './MP3/annie/Annie  Hello Is This The McAfee Support .m4a',
  './MP3/annie/Annie  Hello Is This The Norton Support .m4a',
  './MP3/annie/Annie  Hello Is This The PayPal .m4a',
  './MP3/annie/Annie  It Say s Support  Do I Need To Hit The Enter Button .m4a',
  './MP3/annie/Annie  Message To Say There Was Going To Be A Charge Of 699.00 On My PayPal Account .m4a',
  './MP3/annie/Annie  Now I See My Desktop With My Icons On It .m4a',
  './MP3/annie/Annie  Okay Yes Thank You Soo Much Dear .m4a',
  './MP3/annie/Annie  Okay You Want Me To Close The Google Chrome .m4a',
  './MP3/annie/Annie  Spelling Anydesk .m4a',
  './MP3/annie/Annie  The 3 Dots In The Corner Of Google .m4a',
  './MP3/annie/Annie  Well I Went Down To The Store To Get Some Groceries And I Seen That I Had A Missed Call .m4a',
  './MP3/annie/Annie  Yes Hello  Yes I See Some Kind Of Charge And I Don t Know What It s For It Says 349.99. But I Don t Want This  I Would Like To Get It Cancelled.m4a',
  './MP3/annie/Annie  Yes I ll Be Right Back Thank You .m4a',
  './MP3/annie/Annie  Yes I m At My Computer Yes .m4a',
  './MP3/annie/Annie  Yes I Was Just Looking At My Emails And Looking At Some Things On My Computer .m4a',
  './MP3/annie/Annie  Yes Okay I Did That .m4a',
  './MP3/annie/Annie  Yes That s Fine Sonny  Just Do Whatever You Can Do To Get This Cancelled For Me .m4a',
  './MP3/annie/Annie  Yes Well My Son Pecan Usually Comes Over But He s Away With His Husband Right Now  So I Need The Helps .m4a',
  './MP3/annie/Annie  You Need Me To Login Into My Bank .m4a',
  './MP3/annie/Annie  You Want Me To Close My Email  Okay .m4a',
];

soundboards.Stonewulf_Collection = [
  './MP3/Stonewulf/apple - angry rant hindi.mp3',
  './MP3/Stonewulf/apple - Ben chode.mp3',
  './MP3/Stonewulf/apple - cursing 1.mp3',
  './MP3/Stonewulf/apple - DO YOU GET THIS.mp3',
  './MP3/Stonewulf/apple - gandu.mp3',
  './MP3/Stonewulf/apple - greeting.mp3',
  './MP3/Stonewulf/apple - hindi cursing 1.mp3',
  './MP3/Stonewulf/apple - hindi cursing 2.mp3',
  './MP3/Stonewulf/apple - I beg your pardon.mp3',
  './MP3/Stonewulf/apple - LET ME DO MY JOB.mp3',
  './MP3/Stonewulf/apple - randia.mp3',
  './MP3/Stonewulf/apple - STUPID FOOL.mp3',
  './MP3/Stonewulf/apple - what kind of issue cpu.mp3',
  './MP3/Stonewulf/apple - you bastard.mp3',
  './MP3/Stonewulf/apple - you scoundrel.mp3',
  './MP3/Stonewulf/Baby Chappy.wav',
  './MP3/Stonewulf/BEN CHODE BLOODY.mp3',
  './MP3/Stonewulf/birthday sex-1.mp3',
  './MP3/Stonewulf/BLOODY BASTARD.mp3',
  './MP3/Stonewulf/BLOODY FUCK YOU.mp3',
  './MP3/Stonewulf/buzz off.mp3',
  './MP3/Stonewulf/call me back.mp3',
  './MP3/Stonewulf/cumshot.mp3',
  './MP3/Stonewulf/cursing 1.mp3',
  './MP3/Stonewulf/cursing 2.mp3',
  './MP3/Stonewulf/cursing 3.mp3',
  './MP3/Stonewulf/cursing 4.mp3',
  './MP3/Stonewulf/did you receive the call....mp3',
  './MP3/Stonewulf/Do you understand.mp3',
  './MP3/Stonewulf/egg sandwitch.mp3',
  './MP3/Stonewulf/first... I need to fuck your mom.mp3',
  './MP3/Stonewulf/greeting social security.mp3',
  './MP3/Stonewulf/greeting.mp3',
  './MP3/Stonewulf/haha f--- your mother.mp3',
  './MP3/Stonewulf/have you been to the state of baltimore.mp3',
  './MP3/Stonewulf/hello mother fucker (1).mp3',
  './MP3/Stonewulf/hello1.mp3',
  './MP3/Stonewulf/hindi 4.mp3',
  './MP3/Stonewulf/hindi 5.mp3',
  './MP3/Stonewulf/hold the line let me check it out.mp3',
  './MP3/Stonewulf/i gave your mother 10.mp3',
  './MP3/Stonewulf/i will fuck you.mp3',
  './MP3/Stonewulf/In order todo this first I need to fuck your mom okay1.mp3',
  './MP3/Stonewulf/INTERRUPT 1.mp3',
  './MP3/Stonewulf/INTERRUPT 2.mp3',
  './MP3/Stonewulf/INTERRUPT 3.mp3',
  './MP3/Stonewulf/INTERRUPT 4.mp3',
  './MP3/Stonewulf/Lady - Aha.mp3',
  './MP3/Stonewulf/Lady - Cursing 1.mp3',
  './MP3/Stonewulf/Lady - Cursing 2.mp3',
  './MP3/Stonewulf/Lady - Cursing 3.mp3',
  './MP3/Stonewulf/Lady - Cursing 4.mp3',
  './MP3/Stonewulf/Lady - Cursing 5.mp3',
  './MP3/Stonewulf/Lady - Cursing 6.mp3',
  './MP3/Stonewulf/Lady - Get a fucking life.mp3',
  './MP3/Stonewulf/Lady - Heh.mp3',
  './MP3/Stonewulf/Lady - Hohhh.mp3',
  './MP3/Stonewulf/Lady - Huh.mp3',
  './MP3/Stonewulf/MOTHER BLOODY.mp3',
  './MP3/Stonewulf/mother chode.mp3',
  './MP3/Stonewulf/please press 2 to fuck your girl fiend 1.mp3',
  './MP3/Stonewulf/recorded line.mp3',
  './MP3/Stonewulf/RUNNING LIKE LADY.mp3',
  './MP3/Stonewulf/scam line 1.mp3',
  './MP3/Stonewulf/scam line 2.mp3',
  './MP3/Stonewulf/scam line 3.mp3',
  './MP3/Stonewulf/scam line 4.mp3',
  './MP3/Stonewulf/scam line 5.mp3',
  './MP3/Stonewulf/shut up and fuck off.mp3',
  './MP3/Stonewulf/shut up.mp3',
  './MP3/Stonewulf/suck my dick 1.mp3',
  './MP3/Stonewulf/suck my dick 2.mp3',
  './MP3/Stonewulf/thank you for calling atnt.mp3',
  './MP3/Stonewulf/tu mother chode.mp3',
  './MP3/Stonewulf/we know that.mp3',
  './MP3/Stonewulf/WHY U SALTING AT ME.mp3',
  './MP3/Stonewulf/WHY YOU FUCK ME.mp3',
  './MP3/Stonewulf/write down my name.mp3',
  './MP3/Stonewulf/WTF MAN.mp3',
  './MP3/Stonewulf/yes sir.mp3',
  './MP3/Stonewulf/yes.mp3',
  './MP3/Stonewulf/you got a pen.mp3',
  './MP3/Stonewulf/You know I Fed your mother.mp3',
  './MP3/Stonewulf/you know i.. lol.mp3',
  './MP3/Stonewulf/you mother chode.mp3',
  './MP3/Stonewulf/you think u are smarter than me sob.mp3',
  './MP3/Stonewulf/you want to take that number in your ass.mp3',
  './MP3/Stonewulf/your accent is not like english.mp3',
  './MP3/Stonewulf/your mother told me she slept with 10 different guys.mp3',
];

soundboards.Pecanhead_Collection = [
  './MP3/Pecanhead/a1.mp3',
  './MP3/Pecanhead/a2.mp3',
  './MP3/Pecanhead/a3.mp3',
  './MP3/Pecanhead/a4.mp3',
  './MP3/Pecanhead/a5.mp3',
  './MP3/Pecanhead/a6.mp3',
  './MP3/Pecanhead/a7.mp3',
  './MP3/Pecanhead/aaa.mp3',
  './MP3/Pecanhead/AIRHORN.mp3',
  './MP3/Pecanhead/assless chaps.mp3',
  './MP3/Pecanhead/audio (1).wav',
  './MP3/Pecanhead/audio.wav',
  './MP3/Pecanhead/b1.mp3',
  './MP3/Pecanhead/b2.mp3',
  './MP3/Pecanhead/baby shark dance sing and dance animal songs pinkfong songs for children audiotrimmer.mp3',
  './MP3/Pecanhead/badumtss.swf.mp3',
  './MP3/Pecanhead/Bitch.mp3',
  './MP3/Pecanhead/bo.mp3',
  './MP3/Pecanhead/call me.mp3',
  './MP3/Pecanhead/can i rape you analy.mp3',
  './MP3/Pecanhead/cant believe it.mp3',
  './MP3/Pecanhead/Charlie Cream Pie.mp3',
  './MP3/Pecanhead/charlie master.mp3',
  './MP3/Pecanhead/clown horn sound effect_1.mp3',
  './MP3/Pecanhead/come in naked.mp3',
  './MP3/Pecanhead/couple guys from chicago.mp3',
  './MP3/Pecanhead/DEX DONT GIVE A FK.mp3',
  './MP3/Pecanhead/did an awful nasty awful things and they go written like would down like that they hoped.mp3',
  './MP3/Pecanhead/do u know the movie with a man.mp3',
  './MP3/Pecanhead/donald duck scammer.mp3',
  './MP3/Pecanhead/dont be sure.mp3',
  './MP3/Pecanhead/dont make me beg.mp3',
  './MP3/Pecanhead/dr fell bitch.mp3',
  './MP3/Pecanhead/DR FELL PANTIES.mp3',
  './MP3/Pecanhead/DX DONT GIVE A FK.mp3',
  './MP3/Pecanhead/dx thats what he said.mp3',
  './MP3/Pecanhead/DX WH THE FK.mp3',
  './MP3/Pecanhead/error_CDOxCYm.mp3',
  './MP3/Pecanhead/fat ass.mp3',
  './MP3/Pecanhead/fax.mp3',
  './MP3/Pecanhead/Frank Rizzo open ur ears.mp3',
  './MP3/Pecanhead/freezer.mp3',
  './MP3/Pecanhead/fuck_me_daddy_sick_dropgrabvidtomp3 mp3cut.mp3',
  './MP3/Pecanhead/full extension.mp3',
  './MP3/Pecanhead/geek squad.mp3',
  './MP3/Pecanhead/get on your knees.mp3',
  './MP3/Pecanhead/GET YOUR FAT ASS BACK HERE   AUDIO FROM JAYUZUMI.COM.mp3',
  './MP3/Pecanhead/go ahead please.mp3',
  './MP3/Pecanhead/guess who.mp3',
  './MP3/Pecanhead/guru.mp3',
  './MP3/Pecanhead/h0.mp3',
  './MP3/Pecanhead/h1.mp3',
  './MP3/Pecanhead/h2.mp3',
  './MP3/Pecanhead/h3.mp3',
  './MP3/Pecanhead/h4.mp3',
  './MP3/Pecanhead/h5.mp3',
  './MP3/Pecanhead/h6.mp3',
  './MP3/Pecanhead/h7.mp3',
  './MP3/Pecanhead/h8.mp3',
  './MP3/Pecanhead/h9.mp3',
  './MP3/Pecanhead/HE LOOK LIKE A MAN.mp3',
  './MP3/Pecanhead/hes a piece of shit.mp3',
  './MP3/Pecanhead/hi mam.mp3',
  './MP3/Pecanhead/hi sir.mp3',
  './MP3/Pecanhead/HINDI1.mp3',
  './MP3/Pecanhead/how do you say the flapjack.mp3',
  './MP3/Pecanhead/i dont wear underwear.mp3',
  './MP3/Pecanhead/i knew i was going to become a tranny.mp3',
  './MP3/Pecanhead/i like rape.mp3',
  './MP3/Pecanhead/I WANT TO TALK TO A MANAGER.mp3',
  './MP3/Pecanhead/ill be the best sex you will ever have.mp3',
  './MP3/Pecanhead/im bored and horny.mp3',
  './MP3/Pecanhead/im gonna lick you.mp3',
  './MP3/Pecanhead/im sitting and smoking and watching television.mp3',
  './MP3/Pecanhead/im sorry.mp3',
  './MP3/Pecanhead/laugh1.mp3',
  './MP3/Pecanhead/let it go.mp3',
  './MP3/Pecanhead/like popsicles.mp3',
  './MP3/Pecanhead/mad.mp3',
  './MP3/Pecanhead/mrs swan hello.mp3',
  './MP3/Pecanhead/Ms Swan at Halloween.mp3',
  './MP3/Pecanhead/my cock.mp3',
  './MP3/Pecanhead/nikad sexy.mp3',
  './MP3/Pecanhead/NO SWANN.mp3',
  './MP3/Pecanhead/oh my god.mp3',
  './MP3/Pecanhead/OH THANKS GUY.mp3',
  './MP3/Pecanhead/oh that felt good.mp3',
  './MP3/Pecanhead/OK OK I TELL U.mp3',
  './MP3/Pecanhead/ozzy show us youir cock.mp3',
  './MP3/Pecanhead/peachesnew.mp3',
  './MP3/Pecanhead/piss me off.mp3',
  './MP3/Pecanhead/pistol sound effect_zejYI9w.mp3',
  './MP3/Pecanhead/Police Academy   The Blue Oyster Bar Song.mp3',
  './MP3/Pecanhead/right thats correct.mp3',
  './MP3/Pecanhead/scammer intro microsoft.mp3',
  './MP3/Pecanhead/scammer intro.mp3',
  './MP3/Pecanhead/shit in the laundry.mp3',
  './MP3/Pecanhead/slap you.mp3',
  './MP3/Pecanhead/slinky dinky doo.mp3',
  './MP3/Pecanhead/song i know what boys like.mp3',
  './MP3/Pecanhead/song time of my life.mp3',
  './MP3/Pecanhead/sonic curses.mp3',
  './MP3/Pecanhead/sound fail fallo.mp3',
  './MP3/Pecanhead/south of the border i think they say.mp3',
  './MP3/Pecanhead/stone i suck dick.mp3',
  './MP3/Pecanhead/stone ima transsexual.mp3',
  './MP3/Pecanhead/stupid asshle.mp3',
  './MP3/Pecanhead/swann OK.mp3',
  './MP3/Pecanhead/Takes Scumbag.mp3',
  './MP3/Pecanhead/taser gun electric clicking zaps sparks 2.mp3',
  './MP3/Pecanhead/taser gun electric clicking zaps sparks 5.mp3',
  './MP3/Pecanhead/thats not in his mouth.mp3',
  './MP3/Pecanhead/THATS WH HE SAID DX.mp3',
  './MP3/Pecanhead/the price is right losing horn.mp3',
  './MP3/Pecanhead/This is Frank Rizzo.mp3',
  './MP3/Pecanhead/titanic parody mp3cut.mp3',
  './MP3/Pecanhead/TOUGHY.mp3',
  './MP3/Pecanhead/tylenol.mp3',
  './MP3/Pecanhead/u MF.mp3',
  './MP3/Pecanhead/u MFer 2.mp3',
  './MP3/Pecanhead/u sob asshole.mp3',
  './MP3/Pecanhead/up the fucking ass_OcRd90h.mp3',
  './MP3/Pecanhead/veryloudairhorn.mp3',
  './MP3/Pecanhead/what sort of bird feet do you have.mp3',
  './MP3/Pecanhead/whata sweetheart.mp3',
  './MP3/Pecanhead/where are you.mp3',
  './MP3/Pecanhead/whip his balls out.mp3',
  './MP3/Pecanhead/who the hell are you.mp3',
  './MP3/Pecanhead/why have launches.mp3',
  './MP3/Pecanhead/why you hanging up on me sir.mp3',
  './MP3/Pecanhead/would you ever try anal.mp3',
  './MP3/Pecanhead/yes thats right thats correct.mp3',
  './MP3/Pecanhead/Ylvis   The Fox (What Does The Fox Say) [Official music video HD].mp3',
  './MP3/Pecanhead/you asshole SOB.mp3',
  './MP3/Pecanhead/you know taco bell.mp3',
  './MP3/Pecanhead/you know what im saying.mp3',
  './MP3/Pecanhead/you like doggy.mp3',
  './MP3/Pecanhead/you sob.mp3',
  './MP3/Pecanhead/your neighbor or your friends or maybe relatives would have these things for you to see them.mp3',
  './MP3/Pecanhead/youre a filthy woman.mp3',
];

soundboards.swearing_Indian_Rex_Collection = [
  './MP3/Swearing_indian/Abola Muderchod.mp3',
  './MP3/Swearing_indian/Angery American Man Enjoy making harassment phone calls dont call again.mp3',
  './MP3/Swearing_indian/are you calling me by using a cellphone.mp3',
  './MP3/Swearing_indian/can you please hang up this call from your side sir.mp3',
  './MP3/Swearing_indian/do not ever call okay.mp3',
  './MP3/Swearing_indian/Do you know I am your father.mp3',
  './MP3/Swearing_indian/Do you want to book TicKit x2 TiKiTTiKiTTiKiTTiKiT.mp3',
  './MP3/Swearing_indian/fucking ass hole hindi insults.mp3',
  './MP3/Swearing_indian/Fuck yooooooooou fuck you.mp3',
  './MP3/Swearing_indian/fuck you sir fuck you.mp3',
  './MP3/Swearing_indian/fuuuck off bloody bitch.mp3',
  './MP3/Swearing_indian/get lost from here just get lost.mp3',
  './MP3/Swearing_indian/go and fuck yourself.mp3',
  './MP3/Swearing_indian/hello you mogichod.mp3',
  './MP3/Swearing_indian/how about you let me fuck your daughter and you watch me.mp3',
  './MP3/Swearing_indian/if you want may dick i will give you my dick.mp3',
  './MP3/Swearing_indian/im going to put a popup in ur daughter pussy then i will fix it tonight.mp3',
  './MP3/Swearing_indian/im gonna suck it yes.mp3',
  './MP3/Swearing_indian/im pretty sure youre mentally unstable.mp3',
  './MP3/Swearing_indian/indian scammer insults.mp3',
  './MP3/Swearing_indian/In order todo this first I need to fuck your mom okay.mp3',
  './MP3/Swearing_indian/in your ass i will give you my dick rather than macafeee.mp3',
  './MP3/Swearing_indian/i dont give a damn shit.mp3',
  './MP3/Swearing_indian/i have a dick give your dad mom son ill fuck your familly one by one.mp3',
  './MP3/Swearing_indian/I love techno trance.mp3',
  './MP3/Swearing_indian/I would love to be fucked in my ass.mp3',
  './MP3/Swearing_indian/Jamakin Insults.mp3',
  './MP3/Swearing_indian/jesus christ save me from you fuckers.mp3',
  './MP3/Swearing_indian/just your mom i guess.wav',
  './MP3/Swearing_indian/No no tickets available for you.mp3',
  './MP3/Swearing_indian/Oh that great you can publish that on bbc news.mp3',
  './MP3/Swearing_indian/oh wow wow omg oh wow.mp3',
  './MP3/Swearing_indian/oh your dick in stuck in your friends ass omg your are both doing sex your are doing sex omg.mp3',
  './MP3/Swearing_indian/okaaay you want macafee in my ass okay.mp3',
  './MP3/Swearing_indian/okay so that means you want my dick right.mp3',
  './MP3/Swearing_indian/OMG does he have cancer.mp3',
  './MP3/Swearing_indian/omg your computers got fucked and what about you.mp3',
  './MP3/Swearing_indian/ORB As Prank 1.mp3',
  './MP3/Swearing_indian/ORB As Prank 2.mp3',
  './MP3/Swearing_indian/ORB As Prank 3.mp3',
  './MP3/Swearing_indian/Paypal Paul.mp3',
  './MP3/Swearing_indian/please press 2 to fuck your girl fiend.mp3',
  './MP3/Swearing_indian/rundi lost mind.mp3',
  './MP3/Swearing_indian/senior supervisor fucking your mom and daughter together.mp3',
  './MP3/Swearing_indian/so as i understood that your are a mother fucker your fuck your own mother and you have a sister too click.mp3',
  './MP3/Swearing_indian/so he has cancer in his ass my god and you got cancer in your balls.mp3',
  './MP3/Swearing_indian/so how about you just go ahead and cuck my cock.mp3',
  './MP3/Swearing_indian/so if you are a gay just be proud that you are a gay.mp3',
  './MP3/Swearing_indian/Stop wasting my time you assholes.mp3',
  './MP3/Swearing_indian/what exactly are you trying to doing x2.mp3',
  './MP3/Swearing_indian/Your brother is what gay.mp3',
  './MP3/Swearing_indian/Your computer is going to be fucked got it.mp3',
  './MP3/Swearing_indian/you bloody bitch.mp3',
  './MP3/Swearing_indian/you dont have you email phone name and you calling to find where your macafee.mp3',
  './MP3/Swearing_indian/you have no job i know that.mp3',
  './MP3/Swearing_indian/are you trying to steal the prize.mp3',
  './MP3/Swearing_indian/batty boy.mp3',
  './MP3/Swearing_indian/Cindy possible pch victim voice mail.mp3',
  './MP3/Swearing_indian/cindy youre gonna be a dead bitch by the end of today.mp3',
  './MP3/Swearing_indian/fucking idiot.mp3',
  './MP3/Swearing_indian/have a good day imma be busy trying to get a hold of your guys mom.mp3',
  './MP3/Swearing_indian/hello is it me youre looking for i can see it in your eyes ah battey boy go suck yr muda.mp3',
  './MP3/Swearing_indian/horaaay.mp3',
  './MP3/Swearing_indian/how do you feel to know your a winner.mp3',
  './MP3/Swearing_indian/i said fuck you you fucking whore.mp3',
  './MP3/Swearing_indian/oh ya.mp3',
  './MP3/Swearing_indian/so you should such a stupid just hang up the phone call.mp3',
  './MP3/Swearing_indian/teri maka bola bencalode.mp3',
  './MP3/Swearing_indian/yah fuck you bro fuck you too fuck you hard.mp3',
  './MP3/Swearing_indian/yes im watching you though my crystal ball.mp3',
  './MP3/Swearing_indian/yes same as you i hope you can ask your muder about it.mp3',
  './MP3/Swearing_indian/you answered your self you ask you question to your self that you are a stupid and you answer yah you are de stupid.mp3',
  './MP3/Swearing_indian/you know you a maderchod.mp3',
  './MP3/Swearing_indian/your a fucking idiot.mp3',
  './MP3/Swearing_indian/Angelus 793.MP3',
  './MP3/Swearing_indian/Angelus a one time key 112169.MP3',
  './MP3/Swearing_indian/Angelus Alright.MP3',
  './MP3/Swearing_indian/Angelus and dont release it hold it down.MP3',
  './MP3/Swearing_indian/Angelus and from other finger press.MP3',
  './MP3/Swearing_indian/Angelus and now hold it down.MP3',
  './MP3/Swearing_indian/Angelus But before that.MP3',
  './MP3/Swearing_indian/Angelus Can you please confirm one thing for your safety.MP3',
  './MP3/Swearing_indian/Angelus can you please spell it out i explore.MP3',
  './MP3/Swearing_indian/Angelus can you please spell it out.MP3',
  './MP3/Swearing_indian/Angelus can you repeat word for word what you have written.MP3',
  './MP3/Swearing_indian/Angelus can you see something now.MP3',
  './MP3/Swearing_indian/Angelus can you seee my mouse moving.MP3',
  './MP3/Swearing_indian/Angelus Certified Technician for the windows.MP3',
  './MP3/Swearing_indian/Angelus Check all issues in exact manner.MP3',
  './MP3/Swearing_indian/Angelus click on connect.MP3',
  './MP3/Swearing_indian/Angelus click on it one more time click enter.MP3',
  './MP3/Swearing_indian/Angelus congratulations sir we are connected.MP3',
  './MP3/Swearing_indian/Angelus dont release it.MP3',
  './MP3/Swearing_indian/Angelus four boxes like windows.MP3',
  './MP3/Swearing_indian/Angelus four flags on the left bottom corner.MP3',
  './MP3/Swearing_indian/Angelus Gimme one second.MP3',
  './MP3/Swearing_indian/Angelus Hackers from Jordan and Turkey.MP3',
  './MP3/Swearing_indian/Angelus Hold it down.MP3',
  './MP3/Swearing_indian/Angelus I explore mp3.WAV',
  './MP3/Swearing_indian/Angelus I explore.MP3',
  './MP3/Swearing_indian/Angelus I think you not doing it the right way.MP3',
  './MP3/Swearing_indian/Angelus it says NOTEPAD mp3.WAV',
  './MP3/Swearing_indian/Angelus it says NOTEPAD.MP3',
  './MP3/Swearing_indian/Angelus Mr Robert Mr Bob.MP3',
  './MP3/Swearing_indian/Angelus not forward slash.MP3',
  './MP3/Swearing_indian/Angelus now leave your mouse.MP3',
  './MP3/Swearing_indian/Angelus now type over there let me get the key for you.MP3',
  './MP3/Swearing_indian/Angelus on the right bottom can you see certified support.MP3',
  './MP3/Swearing_indian/Angelus option of run.MP3',
  './MP3/Swearing_indian/Angelus option of YES.MP3',
  './MP3/Swearing_indian/Angelus Press the four flags key.MP3',
  './MP3/Swearing_indian/Angelus Right 6.mp3',
  './MP3/Swearing_indian/Angelus Right.MP3',
  './MP3/Swearing_indian/Angelus shortly notification click it.MP3',
  './MP3/Swearing_indian/Angelus shortly notification click it1.MP3',
  './MP3/Swearing_indian/Angelus space mp3.WAV',
  './MP3/Swearing_indian/Angelus Tanks for holdin the line can you hear me.MP3',
  './MP3/Swearing_indian/Angelus thats the right place sir click on it.MP3',
  './MP3/Swearing_indian/Angelus THE four flags key.MP3',
  './MP3/Swearing_indian/Angelus The reason you are talkin to me right now.MP3',
  './MP3/Swearing_indian/Angelus Till this problem is not fixed.MP3',
  './MP3/Swearing_indian/Angelus uh huh.MP3',
  './MP3/Swearing_indian/Angelus warning alert loop.MP3',
  './MP3/Swearing_indian/Angelus warning alert loop48kHz.WAV',
  './MP3/Swearing_indian/Angelus we are going to help you.MP3',
  './MP3/Swearing_indian/Angelus when you see option at bottom click on save.MP3',
  './MP3/Swearing_indian/Angelus who is this.mp3',
  './MP3/Swearing_indian/Angelus WHY YOU SUCH A DICKHEAD.mp3',
  './MP3/Swearing_indian/Angelus yes i can hear you.mp3',
  './MP3/Swearing_indian/Angelus yes.mp3',
  './MP3/Swearing_indian/Angelus yes1.mp3',
  './MP3/Swearing_indian/Angelus you callin from Michigan.MP3',
  './MP3/Swearing_indian/Angelus You dont need to worry.MP3',
  './MP3/Swearing_indian/Angelus you know boogeyman.mp3',
  './MP3/Swearing_indian/Angelus you want me to fuck your mother.mp3',
  './MP3/Swearing_indian/Angelus YOUR MOTHER WITHOUT CONDOMN.mp3',
  './MP3/Swearing_indian/Angelus on the right bottom the cor-ner.MP3',
  './MP3/Swearing_indian/family motto.mp3',
  './MP3/Swearing_indian/OOOOhYAAAAscammer.wav',
  './MP3/Swearing_indian/hold on x3 give me a moment.mp3',
  './MP3/Swearing_indian/sir it is very tiny.mp3',
  './MP3/Swearing_indian/that heckers want to smell your network.mp3',
  './MP3/Swearing_indian/the hackers want to smell your network and with the help of the smelling they are attracted - they are stealing your financial data.mp3',
  './MP3/Swearing_indian/there are some russian hackers which is connected with you.mp3',
  './MP3/Swearing_indian/yeees yes.mp3',
  './MP3/Swearing_indian/you are asking me what is 783 - thats your mothers pussy code.mp3',
  './MP3/Swearing_indian/i think you are heigh bro.mp3',
  './MP3/Swearing_indian/ill just pull your hair and put you mouth down to your own dick and make you suck it okay.mp3',
  './MP3/Swearing_indian/is this sound is coming from your asshole you motherfucker.mp3',
  './MP3/Swearing_indian/motherfucker.mp3',
  './MP3/Swearing_indian/oh you want to gang bang her.mp3',
  './MP3/Swearing_indian/or you want me to help you out.mp3',
  './MP3/Swearing_indian/so why the fucking you call on this number you fucking ass hole.mp3',
  './MP3/Swearing_indian/suck my dick you motherfucker.mp3',
  './MP3/Swearing_indian/suck your own dick you know how todo it.mp3',
  './MP3/Swearing_indian/teri maka bosada muderchod - hut.mp3',
  './MP3/Swearing_indian/you mother fucker.mp3',
  './MP3/Swearing_indian/MadFemaleScammer YouMothaFucka.mp3',
  './MP3/Swearing_indian/right sir.mp3',
  './MP3/Swearing_indian/scammer breakdown p1.mp3',
  './MP3/Swearing_indian/scammer breakdown p2.mp3',
  './MP3/Swearing_indian/welcom to the playstation stuuport how to i help you.mp3',
  './MP3/Swearing_indian/bark like a dog - bark x3 - bark like a dog x2.mp3',
  './MP3/Swearing_indian/can you see my cock - you like to suck it.mp3',
  './MP3/Swearing_indian/can you send me your dirty x4 panties.mp3',
  './MP3/Swearing_indian/did you like to drink my cum.mp3',
  './MP3/Swearing_indian/do you know what are the components of a computer - ohh i know cuz you dont even have a computer - your a poor guy.mp3',
  './MP3/Swearing_indian/do you think that we are fool here.mp3',
  './MP3/Swearing_indian/donald trump is my father.mp3',
  './MP3/Swearing_indian/dont tech your dad how to fuck.mp3',
  './MP3/Swearing_indian/even i have a left and a right balls buddy - do you have a left and right.mp3',
  './MP3/Swearing_indian/first of all mind your language.mp3',
  './MP3/Swearing_indian/fuck off - fuck your mother.mp3',
  './MP3/Swearing_indian/fuck off bitch and suck your mother.mp3',
  './MP3/Swearing_indian/fuck off you mother fucker.mp3',
  './MP3/Swearing_indian/get lost you mother fucker.mp3',
  './MP3/Swearing_indian/hey shut up you mother fuckers.mp3',
  './MP3/Swearing_indian/hindi insults 2.mp3',
  './MP3/Swearing_indian/hindi insults 3.mp3',
  './MP3/Swearing_indian/hindi insults 4.mp3',
  './MP3/Swearing_indian/hindi insults.mp3',
  './MP3/Swearing_indian/how are you.mp3',
  './MP3/Swearing_indian/how did it explode again.mp3',
  './MP3/Swearing_indian/how you doing - my dick is waiting for you.mp3',
  './MP3/Swearing_indian/i miss my son all the time my son i miss you all the time i know i do some bad things with your mom.mp3',
  './MP3/Swearing_indian/i would be on time everyday x2 sir.mp3',
  './MP3/Swearing_indian/ill give you one rupee hard cash - come - come and meet me some day.mp3',
  './MP3/Swearing_indian/im coming to you home and i will fuck your mother right now okay.mp3',
  './MP3/Swearing_indian/im fine habibi how about you.mp3',
  './MP3/Swearing_indian/im not here to listen all this crap for you.mp3',
  './MP3/Swearing_indian/joe biden is my uncle.mp3',
  './MP3/Swearing_indian/joe biden its my uncle why dont you understand.mp3',
  './MP3/Swearing_indian/just give me your credit card numbers.mp3',
  './MP3/Swearing_indian/let me tell you that maki choot is the eatable things.mp3',
  './MP3/Swearing_indian/macaroni and the cheese virus.mp3',
  './MP3/Swearing_indian/no x3 is that that its your mothersawhore dot com.mp3',
  './MP3/Swearing_indian/no you do one thing sir do you have a windows near by you - first you need to bang your computer on the floor and after throw it away from your windows simple as that - can you do that.mp3',
  './MP3/Swearing_indian/oh well on the bright side you wont need a hammer of a nail you can just use your sons head.mp3',
  './MP3/Swearing_indian/oh you are a gay - right.mp3',
  './MP3/Swearing_indian/ohh my god thank you.mp3',
  './MP3/Swearing_indian/ohh so that mean that your mother was a hoe.mp3',
  './MP3/Swearing_indian/okay i have to go i have a meeting with the donald trump right now.mp3',
  './MP3/Swearing_indian/okay im ready to marry you.mp3',
  './MP3/Swearing_indian/on its stuck up your ass you said - how did it get up your ass - you did a trick shot or something.mp3',
  './MP3/Swearing_indian/or you can suck my balls right now here.mp3',
  './MP3/Swearing_indian/scammer laughing 2.mp3',
  './MP3/Swearing_indian/scammer laughing.mp3',
  './MP3/Swearing_indian/scammer rap 1.mp3',
  './MP3/Swearing_indian/scammer rap 2.mp3',
  './MP3/Swearing_indian/scammer rap 3.mp3',
  './MP3/Swearing_indian/scammer sings i want to break free.mp3',
  './MP3/Swearing_indian/shut up and bend over.mp3',
  './MP3/Swearing_indian/sir i would really appreciate if you could go ahead and speak to me in the proper way - okay - if not i would have to go ahead and disconnect the call.mp3',
  './MP3/Swearing_indian/sir what is the concern you have called us for what reason you have called us today.mp3',
  './MP3/Swearing_indian/sir your voice is breaking could you please repeaty that and speak lounder.mp3',
  './MP3/Swearing_indian/smell it x2 smell my ass comon.mp3',
  './MP3/Swearing_indian/tera maka bola.mp3',
  './MP3/Swearing_indian/teri behnki choot rundike.mp3',
  './MP3/Swearing_indian/that what your mother said to me.mp3',
  './MP3/Swearing_indian/uh i will go and let you know the little recipe about a shrimp virus - are you here to listen that.mp3',
  './MP3/Swearing_indian/what you have todo is put some oil on your ass and put some shrimps in-between that thats the recipe.mp3',
  './MP3/Swearing_indian/why are you making prank calls hang up.mp3',
  './MP3/Swearing_indian/why dont you give me a job to fuck your mama.mp3',
  './MP3/Swearing_indian/yes hi whats up.mp3',
  './MP3/Swearing_indian/you are pretending to be oversmart but i know each and everything.mp3',
  './MP3/Swearing_indian/you are so funny man you are really so funny.mp3',
  './MP3/Swearing_indian/you bloody asshole then why did you give us call.mp3',
  './MP3/Swearing_indian/you have to try a little more harder buddy.mp3',
  './MP3/Swearing_indian/you mother fucker you call me dont call me alright.mp3',
  './MP3/Swearing_indian/you want baby - if you want baby tell me and i can give you baby.mp3',
  './MP3/Swearing_indian/you want to be my habibi.mp3',
  './MP3/Swearing_indian/ah wah-ah wah.mp3',
  './MP3/Swearing_indian/and im the executive here.mp3',
  './MP3/Swearing_indian/chicken burger 1.mp3',
  './MP3/Swearing_indian/chicken burger 2.mp3',
  './MP3/Swearing_indian/chicken burger disconnected.mp3',
  './MP3/Swearing_indian/chicken burger x3.mp3',
  './MP3/Swearing_indian/come to paris.mp3',
  './MP3/Swearing_indian/egg and toast - same x4.mp3',
  './MP3/Swearing_indian/fries coke fanter.mp3',
  './MP3/Swearing_indian/how are you brother how are you.mp3',
  './MP3/Swearing_indian/how may i help you sir.mp3',
  './MP3/Swearing_indian/my name is sam.mp3',
  './MP3/Swearing_indian/okay we are going to block your number dont call here again and again bye bye.mp3',
  './MP3/Swearing_indian/sir what you had in your breakfast.mp3',
  './MP3/Swearing_indian/sir you can simply concern with me like right.mp3',
  './MP3/Swearing_indian/technician disconnected.mp3',
  './MP3/Swearing_indian/that for connecting with geek squad this is allex william how are you doing today.mp3',
  './MP3/Swearing_indian/that you for calling support how may i help you.mp3',
  './MP3/Swearing_indian/uh hu.mp3',
  './MP3/Swearing_indian/unintelligible sounds.mp3',
  './MP3/Swearing_indian/what the problem you have sir - you can simply concern with me.mp3',
  './MP3/Swearing_indian/what.mp3',
  './MP3/Swearing_indian/yes (1).mp3',
  './MP3/Swearing_indian/you want to speak with my manager.mp3',
  './MP3/Swearing_indian/are you alright.mp3',
  './MP3/Swearing_indian/are you fool.mp3',
  './MP3/Swearing_indian/are you on a drugs right now.mp3',
  './MP3/Swearing_indian/are you out of the mind.mp3',
  './MP3/Swearing_indian/are you sick sir.mp3',
  './MP3/Swearing_indian/ask your mom to come and give me a blowjob.mp3',
  './MP3/Swearing_indian/do i have to call 911.mp3',
  './MP3/Swearing_indian/i am telling you what is the truth if you want to belive it or not its up to you.mp3',
  './MP3/Swearing_indian/its up to you im not forcing you to belive anything.mp3',
  './MP3/Swearing_indian/just shutup you big dumb asshole you mother fucker.mp3',
  './MP3/Swearing_indian/okay first of all be calm and explain me - which of problem you have on your computer right now.mp3',
  './MP3/Swearing_indian/okay we are just going to hang up that call and also we are going to block your number byby.mp3',
  './MP3/Swearing_indian/we dont want your target giftcard - if you want to offer something you can offer your pussy bitch.mp3',
];

soundboards.Sound_effect_1 = [
  './MP3/Sound_Effect_1/Sound Effect ambient crowd noise a crowded mall 1 hour.mp3',
  './MP3/Sound_Effect_1/Sound Effect footsteps heels on the pavement walking sound effect heels 1 hour pick relax.mp3',
  './MP3/Sound_Effect_1/Shopping Sound Effect.mp3',
  './MP3/Sound_Effect_1/Shopping Centre.mp3',
  './MP3/Sound_Effect_1/sneaker shoe on concrete floor fast pace.mp3',
  './MP3/Sound_Effect_1/sneaker shoe on concrete floor medium pace.mp3',
  './MP3/Sound_Effect_1/sneaker shoe on concrete floor slow pace 1.mp3',
  './MP3/Sound_Effect_1/sneaker shoe on concrete floor slow pace 2.mp3',
  './MP3/Sound_Effect_1/walmart checkout sfx.mp3',
  './MP3/Sound_Effect_1/StoreClerk.mp3',
  './MP3/Sound_Effect_1/Paying 4 Products.mp3',
  './MP3/Sound_Effect_1/manual banknote counting.mp3',
  './MP3/Sound_Effect_1/Mobile Phone Ringtone.mp3',
  './MP3/Sound_Effect_1/doorbell.mp3',
  './MP3/Sound_Effect_1/keys on door and open.mp3',
  './MP3/Sound_Effect_1/door open close.mp3',
  './MP3/Sound_Effect_1/C&C Generals - Worker Audio.mp3',
];

soundboards.Ultimate_Soundboard = [
  './MP3/Ultimate_Soundboard/2021 04 07 213841761.mp3',
  './MP3/Ultimate_Soundboard/53b1bab6 a8c3 4a1a 82db 7110ce1c29ef 6KNDGWD.mp3',
  './MP3/Ultimate_Soundboard/ahhhhhh.mp3',
  './MP3/Ultimate_Soundboard/alien.mp3',
  './MP3/Ultimate_Soundboard/among us kill sound effect hd slMcZ2v.mp3',
  './MP3/Ultimate_Soundboard/AmongUsDrip.mp3',
  './MP3/Ultimate_Soundboard/AmongUsImposterSound.mp3',
  './MP3/Ultimate_Soundboard/AmongUsMenu.mp3',
  './MP3/Ultimate_Soundboard/andrew tate them.mp3',
  './MP3/Ultimate_Soundboard/anime wow UBX3JJM.mp3',
  './MP3/Ultimate_Soundboard/aplauses.mp3',
  './MP3/Ultimate_Soundboard/are ya winning son lKYd3Fl.mp3',
  './MP3/Ultimate_Soundboard/are you sure about that.mp3',
  './MP3/Ultimate_Soundboard/aroundtheworld.mp3',
  './MP3/Ultimate_Soundboard/AroundTheWorldDaft.mp3',
  './MP3/Ultimate_Soundboard/AwHellNaw.mp3',
  './MP3/Ultimate_Soundboard/ballsofsteel.swf.mp3',
  './MP3/Ultimate_Soundboard/bazinga.swf.mp3',
  './MP3/Ultimate_Soundboard/caillou theme song.mp3',
  './MP3/Ultimate_Soundboard/crazy realistic knocking sound troll twitch streamers small.mp3',
  './MP3/Ultimate_Soundboard/crickets.swf.mp3',
  './MP3/Ultimate_Soundboard/dababy imposter.mp3',
  './MP3/Ultimate_Soundboard/Deepthroat.mp3',
  './MP3/Ultimate_Soundboard/defaultdance bassboosted.mp3',
  './MP3/Ultimate_Soundboard/discord call sound.mp3',
  './MP3/Ultimate_Soundboard/discord join.mp3',
  './MP3/Ultimate_Soundboard/discord leave.mp3',
  './MP3/Ultimate_Soundboard/Discordping.mp3',
  './MP3/Ultimate_Soundboard/dj airhorn sound effect kingbeatz 1.mp3',
  './MP3/Ultimate_Soundboard/DontEverBuyWeed.mp3',
  './MP3/Ultimate_Soundboard/Dropitlikeitshot.mp3',
  './MP3/Ultimate_Soundboard/dry fart.mp3',
  './MP3/Ultimate_Soundboard/ejj.mp3',
  './MP3/Ultimate_Soundboard/Emotes 1   King king congrats 01.ogg',
  './MP3/Ultimate_Soundboard/Emotes 1   King king crying 01.ogg',
  './MP3/Ultimate_Soundboard/Emotes 1   King king happy 01.ogg',
  './MP3/Ultimate_Soundboard/Emotes 1   King king laughter 01.ogg',
  './MP3/Ultimate_Soundboard/Emotes 1   King king mad 01.ogg',
  './MP3/Ultimate_Soundboard/Emotional Damage.mp3',
  './MP3/Ultimate_Soundboard/engineer no01.mp3',
  './MP3/Ultimate_Soundboard/erro.mp3',
  './MP3/Ultimate_Soundboard/fart 1.mp3',
  './MP3/Ultimate_Soundboard/fart with reverb.mp3',
  './MP3/Ultimate_Soundboard/fatality.swf.mp3',
  './MP3/Ultimate_Soundboard/fbi open up sfx.mp3',
  './MP3/Ultimate_Soundboard/five nights at freddys full scream sound 2.mp3',
  './MP3/Ultimate_Soundboard/fort battle pass.mp3',
  './MP3/Ultimate_Soundboard/FuckHerRightInThePussy.mp3',
  './MP3/Ultimate_Soundboard/go suck a dick song vine7 second videos.mp3',
  './MP3/Ultimate_Soundboard/gta san andreas ah shit here we go again BWv0Gvc.mp3',
  './MP3/Ultimate_Soundboard/guy yelling among us sound effect.mp3',
  './MP3/Ultimate_Soundboard/hank sussy baka.mp3',
  './MP3/Ultimate_Soundboard/he needs some milk vine.mp3',
  './MP3/Ultimate_Soundboard/InDaClub.mp3',
  './MP3/Ultimate_Soundboard/Ishowspeedserious.mp3',
  './MP3/Ultimate_Soundboard/jamesmoan.mp3',
  './MP3/Ultimate_Soundboard/jamessalamalackme.mp3',
  './MP3/Ultimate_Soundboard/jamestranny.mp3',
  './MP3/Ultimate_Soundboard/Justin.mp3',
  './MP3/Ultimate_Soundboard/lego yoda death sound effect.mp3',
  './MP3/Ultimate_Soundboard/Lizzies in a box.mp3',
  './MP3/Ultimate_Soundboard/LoveMeLongTime.mp3',
  './MP3/Ultimate_Soundboard/minecraft villager sound effect.mp3',
  './MP3/Ultimate_Soundboard/mission failed well get em next time n5JntMK.mp3',
  './MP3/Ultimate_Soundboard/moan 3.mp3',
  './MP3/Ultimate_Soundboard/moan bark fart.mp3',
  './MP3/Ultimate_Soundboard/MoaningEarrape.mp3',
  './MP3/Ultimate_Soundboard/movie 1.mp3',
  './MP3/Ultimate_Soundboard/mr krabs.mp3',
  './MP3/Ultimate_Soundboard/Mrpostman.mp3',
  './MP3/Ultimate_Soundboard/Mundian to Bach Ke [Bass Boosted].mp3',
  './MP3/Ultimate_Soundboard/my heart will go on hd.mp3',
  './MP3/Ultimate_Soundboard/my movie 6 0RlWMvM.mp3',
  './MP3/Ultimate_Soundboard/mylongestyeahboyever.mp3',
  './MP3/Ultimate_Soundboard/no god please no noooooooooo.mp3',
  './MP3/Ultimate_Soundboard/nokia 2qH81Eb.mp3',
  './MP3/Ultimate_Soundboard/nokia ringtone 1994.mp3',
  './MP3/Ultimate_Soundboard/nokia startup.mp3',
  './MP3/Ultimate_Soundboard/nut ZKo5FA9.mp3',
  './MP3/Ultimate_Soundboard/oh no no no no laugh.mp3',
  './MP3/Ultimate_Soundboard/ohyesdaddy.mp3',
  './MP3/Ultimate_Soundboard/omgwow.mp3',
  './MP3/Ultimate_Soundboard/OneMoreTime.mp3',
  './MP3/Ultimate_Soundboard/perfect fart.mp3',
  './MP3/Ultimate_Soundboard/pornhub community intro.mp3',
  './MP3/Ultimate_Soundboard/preview 4.mp3',
  './MP3/Ultimate_Soundboard/pussy sound effect 1.mp3',
  './MP3/Ultimate_Soundboard/quandale.mp3',
  './MP3/Ultimate_Soundboard/reeeeeeeee.mp3',
  './MP3/Ultimate_Soundboard/Rick Astley   Never Gonna Give You Up (Official Music Video).mp3',
  './MP3/Ultimate_Soundboard/RPReplay Final1649180461.mp3',
  './MP3/Ultimate_Soundboard/run vine sound effect.mp3',
  './MP3/Ultimate_Soundboard/shut the fuck up you cunt better green screen.mp3',
  './MP3/Ultimate_Soundboard/snapchat call.mp3',
  './MP3/Ultimate_Soundboard/snapchat notification sound effect eim6i3us.mp3',
  './MP3/Ultimate_Soundboard/snoop dogg smoke weed everyday.mp3',
  './MP3/Ultimate_Soundboard/sound 9      .mp3',
  './MP3/Ultimate_Soundboard/Still Dre.mp3',
  './MP3/Ultimate_Soundboard/SUIII.mp3',
  './MP3/Ultimate_Soundboard/surprise motherfucker.mp3',
  './MP3/Ultimate_Soundboard/talking ben laugh.mp3',
  './MP3/Ultimate_Soundboard/talking ben saying ben.mp3',
  './MP3/Ultimate_Soundboard/talking benn yes.mp3',
  './MP3/Ultimate_Soundboard/talking bennnn noo.mp3',
  './MP3/Ultimate_Soundboard/tf nemesis.mp3',
  './MP3/Ultimate_Soundboard/TheNextEpisode.mp3',
  './MP3/Ultimate_Soundboard/titanic parody mp3cut.mp3',
  './MP3/Ultimate_Soundboard/tralala 1.mp3',
  './MP3/Ultimate_Soundboard/tuturu 1.mp3',
  './MP3/Ultimate_Soundboard/untitled 1071.mp3',
  './MP3/Ultimate_Soundboard/vibez lets go.mp3',
  './MP3/Ultimate_Soundboard/vine boom.mp3',
  './MP3/Ultimate_Soundboard/vocaroo s1o1nr8lqdq6.mp3',
  './MP3/Ultimate_Soundboard/wet fart 1.mp3',
  './MP3/Ultimate_Soundboard/wetfart slowed.mp3',
  './MP3/Ultimate_Soundboard/what are you doing step bro tik tok meme.mp3',
  './MP3/Ultimate_Soundboard/when the impostor is sus mememe.mp3',
  './MP3/Ultimate_Soundboard/why you bully me every line.mp3',
  './MP3/Ultimate_Soundboard/wii sports bowling nice cock.mp3',
  './MP3/Ultimate_Soundboard/wrong answer sound effect.mp3',
  './MP3/Ultimate_Soundboard/ya like jazz.mp3',
  './MP3/Ultimate_Soundboard/your gay super loud.mp3',
  './MP3/Ultimate_Soundboard/yt1s wU4BGgD.mp3',
  './MP3/Ultimate_Soundboard/yt5s.com damn daniel ar ar ar 128 kbps.mp3',
];

soundboards.Soundboard1 = [
  './MP3/SB/acrow.mp3',
  './MP3/SB/alert microsoft.mp3',
  './MP3/SB/A Fake Microsoft Popup.mp3',
  './MP3/SB/A Fake Popup.mp3',
  './MP3/SB/annoying.mp3',
  './MP3/SB/bbb.mp3',
  './MP3/SB/bear2.mp3',
  './MP3/SB/bell Copy Copy.mp3',
  './MP3/SB/bell Copy.mp3',
  './MP3/SB/bell.mp3',
  './MP3/SB/BELLA.mp3',
  './MP3/SB/Bhenchod Song.mp3',
  './MP3/SB/boathorn.mp3',
  './MP3/SB/boreworms.mp3',
  './MP3/SB/BritMonkey.mp3',
  './MP3/SB/brrruuuuuhhh.mp3',
  './MP3/SB/Burp3.mp3',
  './MP3/SB/busted.mp3',
  './MP3/SB/car crash.mp3',
  './MP3/SB/crowdwow.mp3',
  './MP3/SB/cryingbaby.mp3',
  './MP3/SB/curbyourscamming.mp3',
  './MP3/SB/dagnammit.mp3',
  './MP3/SB/dan whats wrong with you.mp3',
  './MP3/SB/donkey.mp3',
  './MP3/SB/dubludublu.mp3',
  './MP3/SB/evillaugh.mp3',
  './MP3/SB/fart.mp3',
  './MP3/SB/fart2.mp3',
  './MP3/SB/fastphone.mp3',
  './MP3/SB/FBI.mp3',
  './MP3/SB/flashiloveyou.mp3',
  './MP3/SB/free robuk 1.mp3',
  './MP3/SB/frog1.mp3',
  './MP3/SB/german1.mp3',
  './MP3/SB/german2.mp3',
  './MP3/SB/german3.mp3',
  './MP3/SB/givedogahug.mp3',
  './MP3/SB/goat.mp3',
  './MP3/SB/google.mp3',
  './MP3/SB/hello.mp3',
  './MP3/SB/hellomichelle.mp3',
  './MP3/SB/HindiMale1.mp3',
  './MP3/SB/honk.mp3',
  './MP3/SB/horse1.mp3',
  './MP3/SB/howl.mp3',
  './MP3/SB/idoneditit.mp3',
  './MP3/SB/jerkoff.mp3',
  './MP3/SB/khan.mp3',
  './MP3/SB/klaxon.mp3',
  './MP3/SB/laugh.mp3',
  './MP3/SB/laugh3.mp3',
  './MP3/SB/laughserious.mp3',
  './MP3/SB/lipsmacking.mp3',
  './MP3/SB/listentome.mp3',
  './MP3/SB/LoudBirds.mp3',
  './MP3/SB/motherlessgoat.mp3',
  './MP3/SB/nerfherder.mp3',
  './MP3/SB/nokia.mp3',
  './MP3/SB/on fire.mp3',
  './MP3/SB/open fire.mp3',
  './MP3/SB/oz.mp3',
  './MP3/SB/piercingscream.mp3',
  './MP3/SB/pig1.mp3',
  './MP3/SB/playlikegirl.mp3',
  './MP3/SB/PoorKitty.mp3',
  './MP3/SB/popsicle.mp3',
  './MP3/SB/riper.mp3',
  './MP3/SB/rooster crow.mp3',
  './MP3/SB/scream.mp3',
  './MP3/SB/scream2.mp3',
  './MP3/SB/siren.mp3',
  './MP3/SB/swamp.mp3',
  './MP3/SB/terimaakichut.mp3',
  './MP3/SB/TOXIC FLUTE.mp3',
  './MP3/SB/trumpetwah.mp3',
  './MP3/SB/typersbusted.mp3',
  './MP3/SB/wasted.mp3',
  './MP3/SB/wildcat.mp3',
  './MP3/SB/yeehaw.mp3',
  './MP3/SB/you is a scammer.mp3',
  './MP3/SB/you smell.mp3',
];

soundboards.Soundboard2 = [
  './MP3/SB/angel dust aww harder daddy.mp3',
  './MP3/SB/angry4.mp3',
  './MP3/SB/are you serious right now.mp3',
  './MP3/SB/bababooey sound effect.mp3',
  './MP3/SB/badumtss.swf.mp3',
  './MP3/SB/batman on drugs 1.mp3',
  './MP3/SB/c4out4.mp3',
  './MP3/SB/chase.mp3',
  './MP3/SB/dank meme compilation volume 17 cutted.mp3',
  './MP3/SB/deja vu.mp3',
  './MP3/SB/derp 1.mp3',
  './MP3/SB/donald trump fake news sound effect.mp3',
  './MP3/SB/el risitas funniest laugh ever.mp3',
  './MP3/SB/emotional damage.mp3',
  './MP3/SB/nope.mp3',
  './MP3/SB/epic 17.mp3',
  './MP3/SB/fuck this shit im out.mp3',
  './MP3/SB/gayyy.mp3',
  './MP3/SB/get yo fat ass back here.mp3',
  './MP3/SB/goodbadugly whistle long.mp3',
  './MP3/SB/goofy ahhh.mp3',
  './MP3/SB/gunshot1 connor p 8650 hifi.mp3',
  './MP3/SB/hahahahihihihehehe.mp3',
  './MP3/SB/hello your computer has virus sound effect.mp3',
  './MP3/SB/hello its john cena.mp3',
  './MP3/SB/it was at this moment that he he knew he f cked up.mp3',
  './MP3/SB/jerry farts united clean loop original 3 48 hd.mp3',
  './MP3/SB/jettlastkill2.mp3',
  './MP3/SB/kreun.mp3',
  './MP3/SB/laugh funny lol.mp3',
  './MP3/SB/lets go car meme original clip.mp3',
  './MP3/SB/mcdonalds im lovin it jingle.mp3',
  './MP3/SB/movie 1.mp3',
  './MP3/SB/musica elevador short.mp3',
  './MP3/SB/ninja rages at kid sound effects.mp3',
  './MP3/SB/nooo.swf.mp3',
  './MP3/SB/oh my god they killed kenny.mp3',
  './MP3/SB/panjabi mc mundian to bach ke the dictator soundtrack 0s 7s.mp3',
  './MP3/SB/ringtone 7.mp3',
  './MP3/SB/run vine sound effect.mp3',
  './MP3/SB/scooby doo laugh sped up.mp3',
  './MP3/SB/screaming goat.mp3',
  './MP3/SB/shutup.swf.mp3',
  './MP3/SB/snore mimimimimimi.mp3',
  './MP3/SB/sound fail fallo.mp3',
  './MP3/SB/studio audience awwww sound fx.mp3',
  './MP3/SB/surprise motherfucker.mp3',
  './MP3/SB/sweet jesus mr herbert.mp3',
  './MP3/SB/taken i will find you and i will kill you hd.mp3',
  './MP3/SB/technical error.mp3',
  './MP3/SB/thisissparta.swf.mp3',
  './MP3/SB/trollolol.swf.mp3',
  './MP3/SB/wtf boom.mp3',
  './MP3/SB/y2mate.mp3',
  './MP3/SB/yeet sound effect.mp3',
  './MP3/SB/you are an idiot.mp3',
  './MP3/SB/crazy realistic knocking sound troll twitch streamers small.mp3',
  './MP3/SB/evillaugh.swf.mp3',
  './MP3/SB/gun reload sound effect.mp3',
  './MP3/SB/hello motherfucker.mp3',
  './MP3/SB/magicword.mp3',
  './MP3/SB/money 2.mp3',
  './MP3/SB/nein adolf.mp3',
  './MP3/SB/pirate of carbine Flute.mp3',
  './MP3/SB/shut the fuck up.mp3',
  './MP3/SB/spooky scary skeleton.mp3',
  './MP3/SB/windows 10 error sound.mp3',
];

soundboards.Sounds_Songs = [
  './MP3/Songs/ab bol na madarchod.mp3',
  './MP3/Songs/The Bhenchod Song.mp3',
  './MP3/Songs/Useless man song.mp3',
  './MP3/Songs/Useless Man.mp3',
  './MP3/Songs/We are Anonymous Intro HD.mp3',
  './MP3/Songs/virus song on computer.mp3',
];

soundboards.Ear_Raped = [
  './MP3/EAR_RAPED/Bagpipe Music (EAR RAPE).mp3',
  './MP3/EAR_RAPED/BARNEY THEME SONG (EAR RAPE) (BASS BOOSTED).mp3',
  './MP3/EAR_RAPED/Chinese rap meme  earrape (full music).mp3',
  './MP3/EAR_RAPED/Earrape Sound Effects (system startup sound effects).mp3',
  './MP3/EAR_RAPED/Emotional Titanic Flute (EAR RAPE).mp3',
  './MP3/EAR_RAPED/Fireman Sam Theme Song (Ear Rape).mp3',
  './MP3/EAR_RAPED/Illuminati song (Ear Rape)!!!.mp3',
  './MP3/EAR_RAPED/Krusty Crab Song Ear Rape.mp3',
  './MP3/EAR_RAPED/loud indian music.mp3',
  './MP3/EAR_RAPED/Monsters INC (EAR RAPE) [ 1 Hour Loop - Sleep Song ].mp3',
  './MP3/EAR_RAPED/PAW Patrol Theme Song Ear Rape.mp3',
  './MP3/EAR_RAPED/Rick Roll EARRAPE.mp3',
  './MP3/EAR_RAPED/Simpsons Theme Song! (EAR RAPE).mp3',
  './MP3/EAR_RAPED/Spongebob Ear Rape Song.mp3',
  './MP3/EAR_RAPED/SpongeBob theme song  Earrape.mp3',
  './MP3/EAR_RAPED/Thomas The Tank Engine Theme Song (Ear Rape).mp3',
  './MP3/EAR_RAPED/Titanic theme song  Ear Rape.mp3',
  './MP3/EAR_RAPED/Toy story theme (EAR RAPE).mp3',
];

soundboards.Hold_Music = [
  './MP3/Hold_Music/Hold Music and On Hold Music 3 Hours of Best Music on Hold (Volume 1).mp3',
  './MP3/Hold_Music/Hold Music and On Hold Music 1 Hour of Best Music on Hold (Volume 1).mp3',
  './MP3/Hold_Music/Hold Music and On Hold Music 1 Hour of Best Music on Hold.mp3',
  './MP3/Hold_Music/Hold Music with On Hold Music 1 Hour of Best Music on Hold Playlist.mp3',
  './MP3/Hold_Music/Opus Number 1 The Famous Phone Hold Music.mp3',
];
